### PR TITLE
fixed JRM transparency

### LINKED ISSUE #1216: tranaparency option works inconsistently
these don't respect overlay when selected:
image

they respect overlay transparency only if the node is not selected:

but in other tools even when the node segment is selected they are still transparent:

### PR DESCRIPTION
**Pull request by kianzarrin**
fixes #1216 
see issue for details

This is now it looks like now:
image

### CODE REVIEW

File: TLM/TLM/UI/Helpers/TrafficRulesOverlay.cs [hunk 1]
```diff
@@ -138,19 +138,15 @@ private struct SignsLayout {
...
-
                     if (hoveredHandle) {
                         guiColor = Color.Lerp(
                             a: guiColor,
                             b: new Color(r: 1f, g: .7f, b: 0f),
                             t: 0.5f);
                     }
                 }
-                // guiColor.a = TrafficManagerTool.GetHandleAlpha(hoveredHandle);
+                guiColor.a = TrafficManagerTool.GetHandleAlpha(hoveredHandle);
```
Comment (aubergine10) [inline TLM/TLM/UI/Helpers/TrafficRulesOverlay.cs:149]: Considering this is per-sign, we should consider calculating the various transparency values once, when main UI transparency is altered / loaded, rather than per sign. I'll create separate issue detailing that.

Comment (kianzarrin) [reply TLM/TLM/UI/Helpers/TrafficRulesOverlay.cs:149]: 👍

File: TLM/TLM/UI/Helpers/TrafficRulesOverlay.cs [hunk 2]
```diff
@@ -138,19 +138,15 @@ private struct SignsLayout {
...
                     guiColor = Color.Lerp(guiColor, Color.gray, 0.5f);
-                    guiColor.a = TrafficManagerTool.GetHandleAlpha(hovered: false);
                 } else {
-                    // Handles in edit mode are always visible. Hovered handles are also highlighted.
-                    guiColor.a = 1f;
-
                     if (hoveredHandle) {
                         guiColor = Color.Lerp(
                             a: guiColor,
                             b: new Color(r: 1f, g: .7f, b: 0f),
```
[the remark this answers is not in the document]
Comment (kianzarrin) [reply TLM/TLM/UI/Helpers/TrafficRulesOverlay.cs:145]: 👍

**Review by kvakvs — APPROVED** [review]

**Review by krzychu124 — APPROVED** [review]

**Review by aubergine10 — APPROVED** [review]
