### PR TITLE
Parking AI ignores `ElectricCars` district policy and also prevent spawning electric cars at outside connection

### LINKED ISSUE #1527: `Electric Cars` policy does not work as expected with ParkingAI enabled
### Describe the problem

It looks like `ParkingAI` does not ensure that spawned parked residents vehicle in the district with mentioned policy are only electric cars. I've checked the code and found other weird issues but still nothing which could explain that behavior.

### Steps to reproduce

1. Clear parked vehicles and preferably all passenger cars to despawn residents returning home in their "non-environment friendly" vehicles,
2. Paint district and set `Electric Cars` policy
3. From description and the game implementation, if citizen is at home and decided to spawn car it should be electric (`final probability = random.Int(100) < 100 (forced probability when spawning vehicle at building located in the district with mentioned policy)`)

### Notes

Maybe we should also try to force already spawned vehicles (and assigned to resident) to be electric, potential solutions: 
- reset assigned vehicle so it may decide again if want to use car,
- swap it with electric when cim wants to use it

### PR DESCRIPTION
**Pull request by krzychu124**
Fixes #1527 

- bugfix  prevent spawning electric cars for new residents,
- if citizen home is located in a district with `ElectricCars` policy (force use of electric vehicles, requires `Green Cities DLC`) has parked vehicle and tries to use it - swap parked vehicle with electric,

Update: 
- reused vanilla methods for testing if Electric Vehicle should be spawned. Tourists can spawn electric cars same as in vanilla.

Something I found while debugging `ParkingAI`:
- improved `ExtCitizenInstanceManager.IsAtOutsideConnection()`, prevent trying to spawn parked vehicle at outside connection road node - citizen is moving in or leaving the map (wastes time, always fails because of `ParkingAI` requirements for valid parking position)
- reordered code to reduce chance of processing things that might not be used at all - determine `VehicleInfo` only if it can actually be spawned
- improved detection of wrong parked vehicle type in some edge cases. Now they should always use electric car if forced by district policy.
- added null check in case of missing electric car vehicle info (e.g. all disabled with AVO with no replacement)
- swap vehicle info of parked vehicle only when electric vehicle info is available and swapped successfully,

### CODE REVIEW

**Comment by aubergine10** [comment]
Will this affect [Vehicle Wealthizer](https://steamcommunity.com/sharedfiles/filedetails/?id=1633580257) mod by @klyte45

**Comment by krzychu124** [comment]
> Will this affect [Vehicle Wealthizer](https://steamcommunity.com/sharedfiles/filedetails/?id=1633580257) mod by @klyte45

@aubergine10 if source in github repo is not outdated then it's broken since the release date of Harmony migration.

File: TLM/TLM/Manager/Impl/ExtVehicleManager.cs [hunk 1]
```diff
@@ -1094,5 +1094,25 @@ public class ExtVehicleManager
...
+        /// <summary>
+        /// Checks if home building is located in a district that requires electric cars
+        /// </summary>
+        /// <param name="homeBuilding">id of home building</param>
+        /// <param name="isTourist">citizen is tourist - they don't have home</param>
+        /// <returns>true if discrict enforces use of electirc cars
+        /// otherwise false</returns>
+        internal static bool ShouldSpawnElectricCar(ushort homeBuilding, bool isTourist) {
+            // Green cities DLC must be available, required to set ElectricCars district policy
+            if (!Shortcuts.IsGreenCitiesAvailable || isTourist || homeBuilding == 0) {
```
[the remark this answers is not in the document]
Comment (krzychu124) [reply TLM/TLM/Manager/Impl/ExtVehicleManager.cs:1107]: > Also, why must tourist never have electric car?

I'm testing different solution, will be better but slower... I need to check if cim is tourist or resident and then call correct private method via fast delegate so.. avoiding function call here will be more or less pointless micro-optimization compared to a full execution time :/ 
Green Cities DLC is not required to have electric cars - it's only needed if you want to force them in selected district.

File: TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs [hunk 2]
```diff
@@ -1427,34 +1427,37 @@ bool citizenDebug
...
+            bool ret = sourceBuilding.m_flags.IsFlagSet(Building.Flags.IncomingOutgoing) &&
+                       (startPos - sourceBuilding.m_position).sqrMagnitude <= sqrMaxDistToPedestrianLane;
 
-            bool ret = (sourceBuilding.m_flags & Building.Flags.IncomingOutgoing) != Building.Flags.None &&
-                (startPos - sourceBuilding.m_position).magnitude <= parkingAiConf.MaxBuildingToPedestrianLaneDistance;
+            if (!ret) {
+                ref Building targetBuilding = ref instanceData.m_targetBuilding.ToBuilding();
+                ret = targetBuilding.m_flags.IsFlagSet(Building.Flags.IncomingOutgoing) &&
+                      (startPos - targetBuilding.m_position).sqrMagnitude <= sqrMaxDistToPedestrianLane;
+            }
```
Comment (kianzarrin) [inline TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs:1461]: [Note]
a bit of code duplication here. I wonder a local static method would be better:
```cs
static bool IsOutside(ref NetBuilding building, float sqrMaxDistToPedestrianLane) => building.m_flags.IsFlagSet(Building.Flags.IncomingOutgoing) && (startPos - building.m_position).sqrMagnitude <= sqrMaxDistToPedestrianLane;
return IsOutside(ref sourceBuilding, sqrMaxDistToPedestrianLane) || IsOutside(ref targetBuilding, sqrMaxDistToPedestrianLane);
```
Although I am not sure if old Mono would inline this for more performance.

File: TLM/TLM/Manager/Impl/ExtVehicleManager.cs [hunk 3]
```diff
@@ -1094,5 +1100,30 @@ public class ExtVehicleManager
...
             InitAllVehicles();
         }
+
+        /// <summary>
+        /// Checks if citizen should use electric car
+        /// </summary>
+        /// <param name="citizen">Citizen data</param>
+        /// <param name="citizenInstance">CitizenInstance data (spawned instance)</param>
+        /// <returns>true if should use electric car otherwise false</returns>
+        internal bool MustUseElectricCar(ref Citizen citizen, ref CitizenInstance citizenInstance) {
```
Comment (kianzarrin) [inline TLM/TLM/Manager/Impl/ExtVehicleManager.cs:1110]: maybe call this `ShouldUseElectricCar` car?

File: TLM/TLM/Patch/_CitizenAI/_ResidentAI/GetVehicleInfoPatch.cs [hunk 4]
```diff
@@ -106,12 +106,14 @@ public class GetVehicleInfoPatch {
...
             bool useElectricCar = false;
 
+            bool forceElectric = false;
             if (useCar) {
                 int electricProb = GetElectricCarProbability(__instance,
                                                              instanceID,
                                                              ref citizenData,
                                                              __instance.m_info.m_agePhase);
                 useElectricCar = randomizer.Int32(100u) < electricProb;
+                forceElectric = useElectricCar && electricProb == 100;
```
Comment (kianzarrin) [inline TLM/TLM/Patch/_CitizenAI/_ResidentAI/GetVehicleInfoPatch.cs:116]: this is not even marked as NON-STOCK code. had we forgetten to copy code from vanilla?

File: TLM/TLM/Patch/_CitizenAI/_ResidentAI/GetVehicleInfoPatch.cs [hunk 5]
```diff
@@ -126,15 +128,36 @@ public class GetVehicleInfoPatch {
             // NON-STOCK CODE START
             VehicleInfo carInfo = null;
             if (Options.parkingAI && useCar) {
-                ushort parkedVehicleId = citizenData.m_citizen.ToCitizen().m_parkedVehicle;
+                ref Citizen citizen = ref citizenData.m_citizen.ToCitizen();
+                ushort parkedVehicleId = citizen.m_parkedVehicle;
```
Comment (kianzarrin) [inline TLM/TLM/Patch/_CitizenAI/_ResidentAI/GetVehicleInfoPatch.cs:133]: do we need to check if vehicle is valid (has the created flag)?

File: TLM/TLM/Util/Shortcuts.cs [hunk 6]
```diff
@@ -243,5 +243,8 @@ internal static class Shortcuts {
 
             return dlcBitMask;
         }
+
```
Comment (kianzarrin) [inline TLM/TLM/Util/Shortcuts.cs:246]: this is never called

**Review by kianzarrin — CHANGES_REQUESTED** [review]

File: TLM/TLM/Manager/Impl/ExtVehicleManager.cs (hunk 3 above)
Comment (krzychu124) [reply TLM/TLM/Manager/Impl/ExtVehicleManager.cs:1110]: ... it was before

File: TLM/TLM/Manager/Impl/AdvancedParkingManager.cs [hunk 7]
```diff
@@ -2143,6 +2153,24 @@ private ExtSoftPathState
...
+            if (VehicleManager.instance.CreateParkedVehicle(
+                    out ushort parkedVehicleId,
+                    ref Singleton<SimulationManager>.instance.m_randomizer,
+                    electricVehicleInfo,
+                    position,
+                    rotation,
+                    citizenId)) {
+                // releases existing parked car, set new one
+                citizen.SetParkedVehicle(citizenId, parkedVehicleId);
+                parkedVehicleId.ToParkedVehicle().m_flags &= 65527; // update flags (remove all skipping Created)
```
[the remark this answers is not in the document]
Comment (krzychu124) [reply TLM/TLM/Manager/Impl/AdvancedParkingManager.cs:2170]: image

So needs to be written as
```cs
ref VehicleParked parkedVehicle = ref parkedVehicleId.ToParkedVehicle();
parkedVehicle.m_flags = (ushort)((VehicleParked.Flags)parkedVehicle.m_flags & ~VehicleParked.Flags.Parking);
```
I'll change comment...

File: TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs (hunk 2 above)
Comment (krzychu124) [reply TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs:1461]: It won't inline anything. From multiple benchmarks I've created nothing gets inlined on Windows, on Linux/MacOS is more likely (you can notice that in form of crashes while patching things with Harmony).

File: TLM/TLM/Patch/_CitizenAI/_ResidentAI/GetVehicleInfoPatch.cs (hunk 5 above)
Comment (krzychu124) [reply TLM/TLM/Patch/_CitizenAI/_ResidentAI/GetVehicleInfoPatch.cs:133]: CO don't check for it and I don't see any chance for parked vehicle without Created flag.

File: TLM/TLM/Patch/_CitizenAI/_ResidentAI/GetVehicleInfoPatch.cs (hunk 4 above)
Comment (krzychu124) [reply TLM/TLM/Patch/_CitizenAI/_ResidentAI/GetVehicleInfoPatch.cs:116]: No it's custom code...

**Review by kianzarrin — COMMENTED** [review]
code looks good. haven't tested yet

**Comment by aubergine10** [comment]
Can this go in to 11.6.5.2? If so pls add milestone in sidebar.

**Comment by krzychu124** [comment]
> Can this go in to 11.6.5.2? If so pls add milestone in sidebar.

yup, just review and test. I did a lot of tests and debugging. Looks good when running alone.  

---
I also noticed few weird issues while running it and experimenting with bike lanes (cim walked to the intersection closest to position where he parked vehicle and started spamming pathfinding looking for CarPathToParkedVehicle literally 10m away) - need recheck (99.9999% because of shared Car/Bike lane - he thought he is in vehicle while standing on Car/Bike lane 😂)

**Comment by aubergine10** [comment]
> Tourists can spawn electric cars same as in vanilla.

Were tourists able to spawn electric cars prior to this PR?

**Comment by krzychu124** [comment]
> > Tourists can spawn electric cars same as in vanilla.
> 
> Were tourists able to spawn electric cars prior to this PR?

Hmm, they couldn't if `ParkingAI` was active and was not a `DummyTourist`. Citizens moving-in also couldn't spawn electric car at outside connection, so probably only when student grew up and moved out to `ElectricCars` district from family house...

**Comment by krzychu124** [comment]
One more review @kvakvs, @chameleon-tbn, @kianzarrin?

**Review by chameleon-tbn — APPROVED** [review]
Code lgtm

File: TLM/TLM/Patch/_CitizenAI/_ResidentAI/GetVehicleInfoPatch.cs [hunk 8]
```diff
@@ -146,7 +146,11 @@ public class GetVehicleInfoPatch {
                                      () => $"CustomResidentAI.CustomGetVehicleInfo({instanceID}): " +
                                                          $"Force electric! Parked vehicle {parkedVehicleId} is not electric vehicle, wwap with electric one.");
                         // get electric car vehicleInfo
-                        carInfo = Singleton<VehicleManager>.instance.GetRandomVehicleInfo(ref randomizer, service, subService, ItemClass.Level.Level1);
+                        carInfo = Singleton<VehicleManager>.instance.GetRandomVehicleInfo(
+                            ref randomizer,
+                            ItemClass.Service.Residential,
+                            ItemClass.SubService.ResidentialLowEco,
+                            ItemClass.Level.Level1);
```
Comment (kianzarrin) [inline TLM/TLM/Patch/_CitizenAI/_ResidentAI/GetVehicleInfoPatch.cs:153]: why does it have to be level 1?

Comment (krzychu124) [reply TLM/TLM/Patch/_CitizenAI/_ResidentAI/GetVehicleInfoPatch.cs:153]: because all residential vehicles are level1, level2 are car trailers

**Review by kianzarrin — APPROVED** [review]

**Comment by krzychu124** [comment]
I improved detection of wrong parked vehicle type in some edge cases. Now they should always use electric car if forced by district policy.

File: TLM/TLM/Manager/Impl/AdvancedParkingManager.cs [hunk 9]
```diff
@@ -2153,32 +2153,57 @@ private ExtSoftPathState
...
+        /// <param name="electricVehicleInfo">electric vehicle info</param>
+        /// <returns>true only if electric vehicle info exists and parked vehicle was swapped
+        /// otherwise false
+        /// </returns>
+        internal static bool SwapParkedVehicleWithElectric(
                                                     bool logParkingAi,
                                                     uint citizenId,
                                                     ref Citizen citizen,
                                                     Vector3 position,
                                                     Quaternion rotation,
```
Comment (aubergine10) [inline TLM/TLM/Manager/Impl/AdvancedParkingManager.cs:2173]: I'm not sure if it makes any difference here, but passing the `position` (3 x 4 byte) and `rotation` (4 x 4 byte) structs totals 28 bytes. I assume it creates defensive copies of them too?

Would it be better to just pass `ref` to the `VehicleParked` struct (total of 8 bytes)?

**Comment by krzychu124** [comment]
Heh, I thought about possible null vehicle info and slightly refactored behavior for swapping vehicle to eliminate chance of throwing away currently parked vehicle even if it couldn't swap it because of no vehicle info or no free parked vehicle units. 
The user will still see parked cars in areas where district has forced electric cars - I hope they will figure out quickly that electric car assets are required to make the policy work 😅  (better than despawning "wrong" cars or returning null info even if cim had parked vehicle - could cause other weird issues)

You can test again if you want. I'll merge it later in the evening (it's ~4am here xD).

**Comment by aubergine10** [comment]
Is it possible to use colour of existing parked vehicle for the swapped vehicle? Sudden colour changes are going to be much more noticeable than shape changes (eg. if white car turns red, vs. red car changes shape).

File: TLM/TLM/Manager/Impl/AdvancedParkingManager.cs (hunk 9 above)
Comment (krzychu124) [reply TLM/TLM/Manager/Impl/AdvancedParkingManager.cs:2173]: Maybe but.. it's not running in a loop and there are tons of other more memory pressured places in vanilla or TM:PE. 

IMO it's just too small to bother -> creating ref and then dereference takes time so I'm not so sure if it's worth especially when usually vectors or quaternions are passed by ref if you expect to modify it inside the method. 
If struct would have like 10 fields, sure it would have much more sense to me to pass it by ref.

**Comment by krzychu124** [comment]
> Is it possible to use colour of existing parked vehicle for the swapped vehicle? Sudden colour changes are going to be much more noticeable than shape changes (eg. if white car turns red, vs. red car changes shape).

How? What's the probability of generating vehicle with the same/similar color? I think that each vanilla electric car has completely different color variants, you can change it in AVO and we are talking only about swapping cars when you drawn district or added policy **and** cim already has some parked car assigned.

File: TLM/TLM/Manager/Impl/AdvancedParkingManager.cs (hunk 9 above)
Comment (krzychu124) [reply TLM/TLM/Manager/Impl/AdvancedParkingManager.cs:2173]: Also that does not differ too much compared to number of variables you use in the method -> stack of specific size needs to be allocated each time you call the method. 🤷‍♂️

**Comment by aubergine10** [comment]
> How?

Ah, I just checked the code and it's doing `GetColor()` every frame; I had assumed that would happen once and be stored per [parked] vehicle. The color index is based on pseudo-random value based on `vehicleId` to ensure color remains same per instance.

<details><summary>At which point my mind starts going way off track...</summary>

So now I'm wondering how parked vehicle gets the colour of the driving vehicle that just parked? Parked vehicles also get color every frame in the same way - pseudo-random based on parked vehicle id.

It's same vehicle prefab - so same colour choices... how on earth does it ensure the id of parked vehicle results in same color _index_ as the id of driving vehicle does? It can't just use the same id between both states, otherwise slots would never free up for other parked/driving vehicles... can it?

Have vehicles always been changing color when transitioning between parked/driving and I've just not noticed?

</details>

**Comment by krzychu124** [comment]
Heh, no idea how those colors are selected and somehow retained on switches between parked and moving. Might be some magic in randomizer but... it uses SimulationManager randomizer so results are pseudo random compared to initializing Randomizer seed with vehicle ID and taking first value(will return always the same).

Anyways... merging :)
