### PR TITLE
Apply default speed limits to all elevations

### LINKED ISSUE #1226: Speed tool - reset to default setting wrong speed
Note: I'm using current build from PR #1215

### Describe the problem

I've customised default speed for a road, then set custom speed overrides for that road. When I reset to default, the resulting speed is shows an override speed which is slower than the customised default speed.

### Steps to reproduce

1. Set default speed of a road to something other than that defined in prefab - in my case, 30 mph
2. Set override speed to, say 10 mph faster - in my case, 40 mph
3. Use the reset to default tool to try and put road back to the speed set in 1 above
4. It's not giving me that speed - in my case, 20 mph

### Log files

can provide on request

### Savegame?

can provide on request (crazy number of assets + mods)

### Screenshots?

The road is has custom override speed of 40 mph:

image

It's customised default speed is 30 mph:

image

When I reset to default:

image

The resulting speed is showing as customised 20 mph.

image

### Notes or questions?

IIRC the workshop asset speed for this road is 20 mph. Maybe "reset to default" is setting to prefab speed rather than my modified default speed?

Road I'm using is "2 Lane, 2 Way, 15m: No Parking with Bike Lanes" from [UK Small Roads](https://steamcommunity.com/sharedfiles/filedetails/?id=1601040013)

### PR DESCRIPTION
**Pull request by kvakvs**
Fixes #1226 

* Related netinfo names are now calculated for set/reset speed defaults, both child and parent netinfo names are accounted for, restoring entire netinfo tree from any netinfo name, and then setting or clearing speed limits for all of it.
* Refactor: Moved speedlimits data ownership out of [Obsolete] Flags to the speedlimits manager.
* Refactor: New extension methods `MayHaveCustomSpeedLimits` for `NetSegment` and for `NetInfo.Lane`, moved from standalone static method.
* Somewhat hesitant with renames. `NetInfo` is two words but in a function name it looks better as one word `Netinfo`. Same with `SpeedLimits` in a function name they look much better as one word `Speedlimits`. Any agreement on capitals in the naming?

### CODE REVIEW

File: TLM/TLM/Manager/Impl/SpeedLimitManagerExt.cs [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+    /// <summary>Adds extra helper functions to NetSegment and NetInfo.Lane, etc.</summary>
+    public static class SpeedLimitManagerExt {
+        /// <summary>
+        /// Extension method. Call via 'segment.MayHaveCustomSpeedLimits()`.
+        /// Check whether custom speed limits may be assigned to the given segment.
+        /// </summary>
+        /// <param name="segment">Reference to affected segment.</param>
+        /// <returns>True if this segment type can have custom speed limits set.</returns>
+        public static bool MayHaveCustomSpeedLimits(this ref NetSegment segment) {
+            if ((segment.m_flags & NetSegment.Flags.Created) == NetSegment.Flags.None) {
```
Comment (aubergine10) [inline TLM/TLM/Manager/Impl/SpeedLimitManagerExt.cs:11]: Also need to bail if `NetSegment.Flags.Collapsed` is set (road destroyed by a disaster; it is now a pile of rubble).

File: TLM/TLM/UI/SubTools/SpeedLimits/Overlay/OverlaySegmentSpeedlimitHandle.cs [hunk 2]
```diff
@@ -122,20 +122,21 @@
...
+        internal static void SetDefaultSpeedLimit(ushort segmentId,
+                                                  [NotNull] NetInfo netInfo,
+                                                  SetSpeedLimitAction action) {
             switch (action.Type) {
                 case SetSpeedLimitAction.ActionType.SetOverride:
                 case SetSpeedLimitAction.ActionType.Unlimited:
-                    SpeedValue value = action.GuardedValue.Override;
                     bool displayMph = GlobalConfig.Instance.Main.DisplaySpeedLimitsMph;
+                    SpeedValue value = action.GuardedValue.Override;
                     Log.Info($"Setting speed limit for netinfo '{netInfo.name}' seg={segmentId} to={value.FormatStr(displayMph)}");
```
Comment (aubergine10) [inline TLM/TLM/UI/SubTools/SpeedLimits/Overlay/OverlaySegmentSpeedlimitHandle.cs:133]: Should this logging be limited to debug builds? Also, should it log "Setting _default_ speed limit..."

File: TLM/TLM/Manager/Impl/SpeedLimitManagerExt.cs (hunk 1 above)
Comment (kvakvs) [reply TLM/TLM/Manager/Impl/SpeedLimitManagerExt.cs:11]: Collapsed roads can be bulldozed and rebuilt (the speed limit value will be lost), or they can be upgraded in place (then it should be retained). Shall i just throw in that extra flag and it will work?

File: TLM/TLM/UI/SubTools/SpeedLimits/Overlay/OverlaySegmentSpeedlimitHandle.cs (hunk 2 above)
Comment (kvakvs) [reply TLM/TLM/UI/SubTools/SpeedLimits/Overlay/OverlaySegmentSpeedlimitHandle.cs:133]: The idea was to have user actions logged to make the log file more useful. I am fine to keep this debug only, will fix.

File: TLM/TLM/Manager/Impl/SpeedLimitManagerExt.cs (hunk 1 above)
Comment (aubergine10) [reply TLM/TLM/Manager/Impl/SpeedLimitManagerExt.cs:11]: I was today years old when I learnt you could just upgrade collapsed roads instead of bulldoze+rebuild. 😮 

Do we retain the speed when roads are upgraded?

Comment (kvakvs) [reply TLM/TLM/Manager/Impl/SpeedLimitManagerExt.cs:11]: Technically, the value will not be lost on collapse, so it should be retained. I do not own the disasters DLC, the thought of ruining my carefully crafted cities creates internal conflict in me 😂

**Review by krzychu124 — APPROVED** [review]
Cool 👍

**Review by aubergine10 — APPROVED** [review]
Tested in-game, LGTM 👍 

Only issue I found was with AR mod; see issue linked above.

**Review by aubergine10 — CHANGES_REQUESTED** [review]
<details><summary>fixed!</summary>

Actually, found another issue...

I had custom speed override on this road of 20 mph. I reset to default and got 5 mph...

image

However, I'd already customised the default speed of the road to 10 mph...

image

So it looks like resetting a speed override is doing something strange here. I would expect clearing speed override to result in my customised default of 10 mph.

EDIT: And after switching between default vs. override mode using the buttons, it's now showing as override speed of 5 mph:

image

EDIT: If I then change the default to 5 mph, and then back to 10 mph, the segments where I reset overrides now show correct default. Not sure what's going on heh.

The roads are [Parklife Paths as Roads](https://steamcommunity.com/sharedfiles/filedetails/?id=2212198462) assets.

</details>

**Comment by aubergine10** [comment]
Found another issue - this time a bridge prefab didn't get updated when I set default speed for ground segment:

image

The road: [UK Motorways](https://steamcommunity.com/sharedfiles/filedetails/?id=1718180429) id: 1718180429

Bridge: 
image

Ground: 
image

Does the game not have some way already to group prefabs of same road? Eg. for setting elevation when building roads? Maybe Fine Road Anarchy/Tool mods contian some clues?

**Review by aubergine10 — APPROVED** [review]
Default speed limits now correctly apply to elevations.

LGTM 👍

**Comment by aubergine10** [comment]
Hrm, I'm still gettin some weird stuff (not sure if related to this PR). The defaults setting is definitely fixed.

The issue occurs when resetting a segment override to default speed. It's still showing some unusual speed, will report back shortly.

**Comment by aubergine10** [comment]
I'll post here anyway just in case...

<details><summary>speed sign/theme not reverting to default when resetting a segment override speed</summary>

These roads are 30mph default speed:

image

This is the overrides that are in place prior to resetting:

image

After resetting that segment, it was still showing 20mph. Maybe there is issue with speed conversion somewhere when resetting? Or missing info refresh?

Here I am about to reset a 25mph override (the road default is 30mph as shown in earlier image):

image

Again, speed icon shows override (british themed) 25mph after resetting.

If I then change default speed of those roads from 30 mph to 10 mph, then back to 30 mph...

image

The icons now show correct default speed for the roads when I go back to segment override mode (see above).

So it looks like reset overrides aren't updating until I make subsequent changes to the defaults, then they show whatever the default speed is. For example, setting road default speed to 15 and they correctly show 15 when segment override mode is selected:

image

So the icon update issue is only occurring after:

1. Set default speed to something
2. Reset the segment override (I assume same issue with lane override)
3. Segment speed doesn't reflect default speed - icon theme and speed are still previous override values
4. Alter default speeds to anything else, even then change back to what the default speed previously was, and the icons now correctly show default speed in override mode

Apologies for long post, just trying to provide as much infos as possible.

</details>

File: TLM/TLM/Manager/Impl/SpeedLimitManager.cs [hunk 3]
```diff
@@ -397,65 +257,56 @@ or ItemClass.SubService.PublicTransportMetro
...
-                out List<string> childNetInfoNames)) {
-                foreach (string childNetInfoName in childNetInfoNames) {
-                    if (netInfoByName_.TryGetValue(childNetInfoName, out NetInfo childNetInfo)) {
+            foreach (var netinfo2 in GetCustomisableRelatives(netinfo)) {
+                string netinfoName = netinfo2.name;
+                customLaneSpeedLimit_[netinfo2.name] = customSpeedLimit;
+
 #if DEBUGLOAD
-                        Log._Debug($"Updating child NetInfo {childNetInfoName}: Setting speed limit to {gameSpeedLimit}");
+                Log._Debug($"Updating parent NetInfo {netinfoName}: Setting speed limit to {gameSpeedLimit}");
```
Comment (kianzarrin) [inline TLM/TLM/Manager/Impl/SpeedLimitManager.cs:305]: this is not necessarily parent netinfo. Id remove the parent from this sentence

Comment (kvakvs) [reply TLM/TLM/Manager/Impl/SpeedLimitManager.cs:305]: Removed

**Comment by kvakvs** [comment]
@aubergine10 I have hard time to reproduce this last problem (did not reproduce).
Did you modify lane speeds on the same segment? It could show averaged speed for all lanes which might look like (20)

**Comment by aubergine10** [comment]
@kvakvs ; No, I thought that too, but tested on lanes where only segment speed was overridden. I'm not sure if it's side effect of me keep switching between different builds of the mod.

Maybe it only happens after load?

Example:

* Set default speed for road
* Apply segment override
* Save game, quit to desktop
* Relaunch cities, load city
* Reset the segment speed (should go back to default, but for me it rarely does)

Also, did you try it on MPH speed setting? Maybe there is a conversion unit glitch in there somewhere?

**Comment by kvakvs** [comment]
Vanilla lane speed limits are re-created in the `SpeedLimitManager.OnBeforeLoadData` and it takes from the netinfo lane speeds. This is also where we store the defaults while the simulation is running. So if you reload the map without restarting the game, I think it will happily forget old "defaults" and accept the "new" whatever it was in the asset lane data.

**Comment by kianzarrin** [comment]
> Reset the segment speed (should go back to default, but for me it rarely does)

@aubergine10 I cannot reproduce this. what do you mean reset segment speed ? what do you mean it should go back to default. if you are resetting the speed limit for that segment (and not for road type) it should go back the CUSTOM default speed limit you set for it earlier.

**Comment by aubergine10** [comment]
>  it should go back the CUSTOM default speed limit you set for it earlier.

Yeh, that's the problem - after loading a save, when I reset a segment speed override (expecting it to go back to my customised default speed for that network) it's going to some other value (occasionally) or the speed sign just isn't updating.

So I'd set _custom default_ of 30 mph.

And override segment to like 25 mph or something.

Load city with that setup, reset the 25mph... I'm expecting green 30mph sign to appear... but instead I still have (most often) a themed (speed override) 25 mph sign there. Sometimes it's a themed sign but some other speed, like 20 mph or something (that happens rarely).

So I then go change the default speed to anything else, and that seems to jolt it in to working properly again - now when I reset a speed override it will show the green custom default speed.

I'll try and take a vid next time I'm in-game to show exactly what is going on. But it's definitely doing something wierd - for me at least - espeically after loading a save. 

Here's log file btw, if that's any use...  
[output_log.zip](https://github.com/CitiesSkylinesMods/TMPE/files/7761280/output_log.zip)

**Comment by kvakvs** [comment]
The speeds and the defaults on segments are not cached anywhere.
The themed speed sign can show if the override speed returned by the SLManager doesn't match the default for that road returned by the SLManager at the rendering time.
There could be a bug in speed limit override or speed limit default retrieval code, but really tricky to reproduce using default road assets

**Comment by kianzarrin** [comment]
it would be nice if you try to see if you can reproduce using minimal test case.

**Comment by kianzarrin** [comment]
I can't reproduce: https://rumble.com/vr8afx-speed-limits.html

**Comment by aubergine10** [comment]
> The comparison precision might be at play here, its float comparison with quite small error margin if i remember correct.

Maybe needs something like this?

https://github.com/Quistar-LAB/EManagersLib/blob/master/EMath.cs#L36

> it would be nice if you try to see if you can reproduce using minimal test case.

Actually, I think I worked out what's happening... It's nothing to do with the speed default, it's the km/h vs. mph settings...

bandicam 2021-12-22 18-39-52-815

It's showing MPH on the speed panel (correct, I was using MPH last save)... But the icon theme is US km/h. No wonder it's getting confused... MPH and km/h at same time `"/`

So now the reproduction steps might be:

1. Set MPH with UK themed icons
2. Customise default road speeds
3. Set some segment overrides to different speed
4. Save city, exit to desktop
5. Restart app, load city
6. Try resetting defaults

**Comment by aubergine10** [comment]
Link to vid showing the issue (note, since my comment above, I'd changed the icon theme to british):

https://i.imgur.com/JkjGxTq.mp4

I wiggled the camera viewport so it's unlikely to be viewport caching (dunno if we have that yet?).

The roads I'm using are these (I think there's only one asset in the pack with bike lanes): https://steamcommunity.com/sharedfiles/filedetails/?id=1601040013

The roads have been customised with intersection marking tool and BOB (to replace street lights which on those roads are weirdly rotated hence not using NS2)

**Comment by kianzarrin** [comment]
Is it reproducable with vanilla roads?

**Comment by kvakvs** [comment]
> It's showing MPH on the speed panel (correct, I was using MPH last save)... But the icon theme is US km/h. No wonder it's getting confused... MPH and km/h at same time `"/`

USA uses miles per hour

I'll try reproducing today or tonight again, and if you have a moment, a TMPE log could help, it should contain those debug lines of setting/clearing speed limits on segments and lanes. And maybe you can comment which log timestamp is when the problem appears.

**Comment by aubergine10** [comment]
[output_log.zip](https://github.com/CitiesSkylinesMods/TMPE/files/7768266/output_log.zip)

**Comment by aubergine10** [comment]
@kvakvs I think adding the `Approximately` function to speed comparisons (to deal with tiny rounding errors) might solve some of the sign-update issues (eg. in cases where resetting to custom default is working, but custom sign theme is still shown). https://github.com/Quistar-LAB/EManagersLib/blob/master/EMath.cs#L36

As for the other issue, where resetting seems to cause strange results, I'm noticing that once I sort that out (setting default to some other value, then back to desired value, then doing a reset) and save, that network starts behaving normally again next time I load the city. So perhaps there was some corrupt data in there from testing other builds?

Regarding US signs having mph variant, I forgot about that, sorry. I'll update the docs. How does it decide what variants are available - is it just based on what signs are available, or is there a lookup table somewhere? Eg. if a sign pack has 10..140 signs, does that automatically mean it can do both mph and km/h?

**Comment by aubergine10** [comment]
> Is it reproducable with vanilla roads?

@kianzarrin I've only got a handful of vanilla roads and I'm not noticing any problems on those; so it could potentially be issue with the workshop roads I'm using (UK roads - linked in earlier comment). It's known that they have some issues (eg. direction `both` on parking lanes) but so far I'm not aware of any issues with their vehicle lanes. I can't see anything particularly different about their road lanes via Network Detective mod.

**Comment by kvakvs** [comment]
> > Is it reproducable with vanilla roads?
> 
> @kianzarrin I've only got a handful of vanilla roads and I'm not noticing any problems on those; so it could potentially be issue with the workshop roads I'm using (UK roads - linked in earlier comment). It's known that they have some issues (eg. direction `both` on parking lanes) but so far I'm not aware of any issues with their vehicle lanes. I can't see anything particularly different about their road lanes via Network Detective mod.

Now wait a moment. Speed limits on segments are set/reset using calling apply speed limit twice on direction Forward and direction Back.

**Comment by kianzarrin** [comment]
> I've only got a handful of vanilla roads and I'm not noticing any problems on those

Excellent. this information can helps us to reproduce the problem. So we need those specific WS roads.

**Comment by kianzarrin** [comment]
> Netinfo hierarchy

This might be a picky comment but I think hierarchy in the title of the PR is confusing.
"Apply default speed limits to all elevations" might be a simpler title.

**Comment by kianzarrin** [comment]
@krzychu124  how do I get the tmpe.zip for this PR (its a fork so I don't know how)?

**Comment by aubergine10** [comment]
@kianzarrin does this not work? https://ci.appveyor.com/project/krzychu124/tmpe/builds/41975399/artifacts

**Comment by kianzarrin** [comment]
Does that point to the latest build every time the branch get updated

**Comment by aubergine10** [comment]
Yup, I think so. It's a zip made at end of CI process.   
image

**Comment by krzychu124** [comment]
> @krzychu124 how do I get the tmpe.zip for this PR (its a fork so I don't know how)?
> 
> this does not work: https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=kvakvs:bug/speedlimits-related-netinfos

You can use `branch` param alias only if the branch was created in the TMPE repo. 
If branch is from the outside use that button (see screenshot) and then get build from `Artifacts` tab. Zip file available in `Artifacts` tab is from that concrete build (deleted every month automatically because of free plan of Appveyor CI).
image

**Comment by aubergine10** [comment]
After a few more days testing, it seems that the problem has subsided (with weird results when reverting to default speed). The data must have become corrupt or something, and altering the default speed of roads seems to have flushed that issue away.

The only remaining problem I have is that there are occasional roads which still show customised (themed) speed sign when reverted to default (although it shows correct speed). Possibly result of tiny rounding errors mentioned in earlier comments.

**Comment by kvakvs** [comment]
Going to merge this
Let's then merge themes branch and see if the problem is still there and needs fixing
