### PR TITLE
Cargo truck transfer pathfinding fixes

### LINKED ISSUE #1701: Default vehicle restrictions break cargo tuck transport through cargo station (train/plane/ship)
### Describe the problem
As in title, there is something going really wrong with cargo truck pathfinding which suppose to generate mixed path (with train/plan/ship parts).. One issue is `CanUseLane` that is comparing allowed `RailVehicle` with `CargoTruck` which obviously fails so higher or _Strict_ vehicle restrictions aggression setting can break paths (at **low** it still collects penalties but still might work for shorter paths). Completely disabled feature doesn't fully solve the problem as in certain conditions path might not be found unlike in vanilla (without TMPE).

**_Code responsible for initial problem is quite old but there is a chance that one of the recent changes/patches could just reveal the problem present already from the first implementation of the vehicle restrictions feature._**

### Conclusions 

1. Setting vehicle restriction aggression any option above **Low** increases change of failed paths,
2. Disabling vehicle restrictions feature doesn't seem to fully fix the problem - in certain conditions path may still fail
3. Vanilla works perfectly, length of path or multiple transport type switching doesn't play any significant role

### Log files

No log, it's not something that throws traceable errors.

### Savegame?

Good example test case (Airports DLC and Industries DLC are required to run it because of used dlc assets)
https://forum.paradoxplaza.com/forum/threads/cities-skylines-steam-airport-dlc-cargo-train-terminal-never-spawn-trucks-with-load.1558724/post-28638023

### Screenshots?
**With TM:PE (disabled vehicle restrictions)** notice that in certain but weird conditions path does not appear (not found)

https://user-images.githubusercontent.com/19638970/204152898-0976ddfd-8231-4f7b-9311-9ea0857fcb8c.mp4

**Vanilla:**

https://user-images.githubusercontent.com/19638970/204152873-e625a4a2-893a-4410-9628-e408c078bb40.mp4

### Notes

I use slightly modified bus tool - patched `TransportLaneAI.StartPathfind` to query for path with exactly the same parameters as normally cargo truck use which obviously helps visualizing final path (if exist) instead of digging in the pathfinding logs.

### PR DESCRIPTION
**Pull request by krzychu124**
Fixes #1701 

- fixes pathfinding issue when searching for cargo path with use of multiple types of cargo transport (train/plane/ship) 
- improves lane routing via `CargoVehicle` lanes which solves issues for buildings that suppose to allow for pass through vehicle paths like cargo terminals but also Airports DLC dual track Cargo Train Station 

### Note

I've swapped method for matching lanes for `RoutingManager`, because the original was already used by lane connection tool (and more) and I didn't want to increase complexity or scope of tests.
Additionally lanes with `CargoVehicles` are not available for configuration in game by any tools we support and at this state they are used internally only in form of invisible paths included in building assets and meant to be used as internal paths with certain limitations. 

More info about the problem and small test savegame you can find in the mentioned issue.

Build [ZIP](https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=bugfix/1701-cargo-truck-transfer-mixed-path-issues)

### CODE REVIEW

File: TLM/TLM/Util/TrackUtils.cs [hunk 1]
```diff
@@ -17,22 +17,31 @@ internal static class TrackUtils {
             VehicleInfo.VehicleType.Monorail;
 
         internal const NetInfo.LaneType ROAD_LANE_TYPES = LaneArrowManager.LANE_TYPES;
+        internal const NetInfo.LaneType ROUTED_ROAD_LANE_TYPES = LaneArrowManager.LANE_TYPES | NetInfo.LaneType.CargoVehicle;
```
Comment (kianzarrin) [inline TLM/TLM/Util/TrackUtils.cs:20]: maybe we should just use the one in routing manger instead of duplicate values.

Comment (krzychu124) [reply TLM/TLM/Util/TrackUtils.cs:20]: Hmm, I was thinking about that, but on the other hand we already use `MatchesTrack` from here in the Routing Manager...
Anyways.. TrackUtils class is not the best class name if we collect both, track and road helpers 😄

Comment (kianzarrin) [reply TLM/TLM/Util/TrackUtils.cs:20]: I was struggling with the naming of this class. It was to distinguish track from road.

File: TLM/TLM/Custom/PathFinding/CustomPathFind.cs [hunk 2]
```diff
@@ -289,8 +291,16 @@ private struct BufferItem {
                 disableMask_ |= NetSegment.Flags.Flooded;
             }
 
+            allowMixedCargoPath_ = false;
+            mixedPathVehicleTypes_ = queueItem_.vehicleType;
             if ((laneTypes_ & NetInfo.LaneType.Vehicle) != NetInfo.LaneType.None) {
                 laneTypes_ |= NetInfo.LaneType.TransportVehicle;
+
+                // allowed mixed vehicle path when requeted path is Vehicle + CargoVehicle (at current state CargoTruck and PostVanAI)
```
Comment (kianzarrin) [inline TLM/TLM/Custom/PathFinding/CustomPathFind.cs:299]: requeted -> requested

Comment (kianzarrin) [reply TLM/TLM/Custom/PathFinding/CustomPathFind.cs:299]: allowed -> allow

Comment (kianzarrin) [reply TLM/TLM/Custom/PathFinding/CustomPathFind.cs:299]: if you replace `at current state` with `E.g.:` your comment will be future proof :)

File: TLM/TLM/Custom/PathFinding/CustomPathFind.cs [hunk 3]
```diff
@@ -4088,15 +4098,41 @@ private struct BufferItem {
                 return true;
             }
 
-            ExtVehicleType allowedTypes = vehicleRestrictionsManager.GetAllowedVehicleTypes(
+            ExtVehicleType allowedPathVehicleTypes = allowMixedCargoPath_
+                                                        ? mixedPathVehicleTypes_
+                                                        : queueItem_.vehicleType;
```
Comment (kianzarrin) [inline TLM/TLM/Custom/PathFinding/CustomPathFind.cs:4103]: it seems to me if `allowMixedCargoPath_ `is false then `mixedPathVehicleTypes_  == queueItem_.vehicleType` because of this code from earlier on:
```cs
if (allowMixedCargoPath_) {
  mixedPathVehicleTypes_ = VehicleTypeToMixedCargoExtVehicle(vehicleTypes_, queueItem_.vehicleType);
}
```
therefore this line can be simplified to:
```suggestion
            ExtVehicleType allowedPathVehicleTypes = mixedPathVehicleTypes_;
```
maybe also rename `mixedPathVehicleTypes_ `to `allowedPathVehicleTypes_` or add a comment.

File: TLM/TLM/Custom/PathFinding/CustomPathFind.cs [hunk 4]
```diff
@@ -4088,15 +4098,41 @@ private struct BufferItem {
...
+
+            ExtVehicleType allowedLaneVehicleTypes = vehicleRestrictionsManager.GetAllowedVehicleTypes(
```
Comment (kianzarrin) [inline TLM/TLM/Custom/PathFinding/CustomPathFind.cs:4105]: `VehicleRestrictionsManager` does not make use of `LaneType.CargoVehicle` at all. why is that?

File: TLM/TLM/Custom/PathFinding/CustomPathFind.cs (hunk 3 above)
Comment (krzychu124) [reply TLM/TLM/Custom/PathFinding/CustomPathFind.cs:4103]: The main reason for that is to help understanding that is specific behavior, applied only for specific vehicles in specific condition. If generalize it, it will become even more confusing if you back to the code after some time.

File: TLM/TLM/Custom/PathFinding/CustomPathFind.cs [hunk 5]
```diff
@@ -289,8 +291,16 @@ private struct BufferItem {
...
 
+            allowMixedCargoPath_ = false;
+            mixedPathVehicleTypes_ = queueItem_.vehicleType;
             if ((laneTypes_ & NetInfo.LaneType.Vehicle) != NetInfo.LaneType.None) {
                 laneTypes_ |= NetInfo.LaneType.TransportVehicle;
+
+                // allowed mixed vehicle path when requeted path is Vehicle + CargoVehicle (at current state CargoTruck and PostVanAI)
+                allowMixedCargoPath_ = (laneTypes_ & NetInfo.LaneType.CargoVehicle) != NetInfo.LaneType.None;
+                if (allowMixedCargoPath_) {
+                    mixedPathVehicleTypes_ = VehicleTypeToMixedCargoExtVehicle(vehicleTypes_, queueItem_.vehicleType);
```
[the remark this answers is not in the document]
Comment (krzychu124) [reply TLM/TLM/Custom/PathFinding/CustomPathFind.cs:302]: It's like that only because I found another bug in the code recently.

File: TLM/TLM/Custom/PathFinding/CustomPathFind.cs (hunk 4 above)
Comment (kianzarrin) [reply TLM/TLM/Custom/PathFinding/CustomPathFind.cs:4105]: Silly me. I confused `VehicleRestrictionsManager` with `VehicleBehaviourManager` because I was tired last night.

File: TLM/TLM/Custom/PathFinding/CustomPathFind.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (kianzarrin) [reply TLM/TLM/Custom/PathFinding/CustomPathFind.cs:302]: so it was a oversight huh? are you going to change it?

[the remark this answers is not in the document]
Comment (kianzarrin) [reply TLM/TLM/Custom/PathFinding/CustomPathFind.cs:302]: so it was an oversight? are you going to fix this?
or are you trying my suggestion is somehow a bug?

[the remark this answers is not in the document]
Comment (krzychu124) [reply TLM/TLM/Custom/PathFinding/CustomPathFind.cs:302]: @kianzarrin I was meant the code was written like that and made sense, but only before I found a bug which changes a lot of things, and now.. it can be simplified as you've pointed out.

File: TLM/TLM/Util/TrackUtils.cs (hunk 1 above)
Comment (krzychu124) [reply TLM/TLM/Util/TrackUtils.cs:20]: I'll leave it like it is for now, there are some plans for mixing trains on road, so maybe we will need to rethink the whole logic if needed. It's not a big issue.

**Review by kianzarrin — APPROVED** [review]
except for the minor readability issue LGTM

**Review by kvakvs — APPROVED** [review]
