### PR TITLE
Yield behaviour improvements

### LINKED ISSUE #756: Yield signs broken (again?)
### Describe the problem
Yield signs don't work as expected. Cars inside a roundabout (for example) give way to cars incoming to the roundabout even if there is a priority sign for cars on that roundabout and a yield sign for the incoming traffic. 

### Steps to reproduce

1. Build a roundabout
2. Place the priority signs
3. Wait 

### Log files

[Log_Files.zip](https://github.com/CitiesSkylinesMods/TMPE/files/4270765/Log_Files.zip)

### Savegame?

https://steamcommunity.com/sharedfiles/filedetails/?id=2010509718

### Notes or questions?

The problem came back with 11.1.1 v.

### PR DESCRIPTION
**Pull request by krzychu124**
Closes #756 

Improves vehicle yield behaviour.

### CODE REVIEW

File: TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs [hunk 1]
```diff
@@ -1549,62 +1549,61 @@ IJunctionRestrictionsManager junctionRestrictionsManager
                             if (logPriority) {
                                 Log._Debug(
                                     $"VehicleBehaviorManager.MayChangeSegment({frontVehicleId}): " +
-                                      $"{sign} sign. waittime={extVehicle.waitTime}");
+                                    $"{sign} sign. waittime={extVehicle.waitTime}");
```
Comment (aubergine10) [inline TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs]: This would be better as `Log._DebugFormat()`?

**Comment by aubergine10** [comment]
Tested in-game and seems to work well. Vehicles slow a little but don't stop, which seems correct behaviour.

File: TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs (hunk 1 above)
Comment (krzychu124) [reply TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs]: Ok, I can't change it to `DebugIf` because extVehicle is `ref` variable and reference variable cannot be used in lambda expressions.
