### PR TITLE
Main Camera cache reinitialization to prevent use of inactive camera

### LINKED ISSUE #1078: Lane connector tool raycasting problem when Dynamic Resolution mod enabled
### Describe the problem

Lane connection tool raycasing problem when [Dynamic Resolution](https://steamcommunity.com/sharedfiles/filedetails/?id=812713438) mod used (value other than 100%)

### Steps to reproduce

1. Subscribe to Dynamic Resolution mod
2. Change resolution to any other significant value other than 100%, e.g. 80,120,150, etc
3. Enable Lane connector tool and try to click on the lane to begin connection

### Log files
No errors or any other useful info

### Savegame?

No need, can be reproduced on new game with TM:PE and Dynamic Resolution mod

### PR DESCRIPTION
**Pull request by krzychu124**
For more info see #1078

Resolves #1078

### CODE REVIEW

**Review by kianzarrin — APPROVED** [review]
nice

File: TLM/TLM/UI/TrafficManagerTool.cs [hunk 1]
```diff
@@ -323,6 +323,14 @@ public class TrafficManagerTool
                     e.Value.Cleanup();
                 }
             }
+
+            // Disabled camera may indicate the main camera change.
+            // Reinitialize camera cache to make sure we will use the correct one
+            if (!InGameUtil.Instance.CachedMainCamera.enabled) {
+                Log.Info("CachedMainCamera disabled - camera cache reinitialization");
```
Comment (DaEgi01) [inline TLM/TLM/UI/TrafficManagerTool.cs:330]: why log?

**Review by DaEgi01 — APPROVED** [review]

File: TLM/TLM/UI/TrafficManagerTool.cs (hunk 1 above)
Comment (krzychu124) [reply TLM/TLM/UI/TrafficManagerTool.cs:330]: Why not, it's internal info, at worst it will be single occurrence, but may suggest possible place necessary to check when the user report issues with raycasiting or other screen resolution/main camera dependent features

Comment (DaEgi01) [reply TLM/TLM/UI/TrafficManagerTool.cs:330]: if you assume it will help you debug user issue, kk.

**Review by chameleon-tbn — APPROVED** [review]
lgtm
