### PR TITLE
fixed iteration exception when clicking on handles

### LINKED ISSUE #744: clicking on vehicle restriction handles throws hidden exception
see https://github.com/CitiesSkylinesMods/TMPE/pull/721#pullrequestreview-364408877
we should also check for other tools too.

### PR DESCRIPTION
**Pull request by kianzarrin**
fixes #744

I break after update segment list is updated to avoid exception. next loop will have a fresh start.

I can confirm that we don't get similar exceptions in speed limit tool or parking tool.

### CODE REVIEW

File: TLM/TLM/UI/SubTools/VehicleRestrictionsTool.cs [hunk 1]
```diff
@@ -248,15 +247,11 @@ public VehicleRestrictionsTool(TrafficManagerTool mainTool)
                 }
 
                 if (update) {
-                    updatedSegmentId = segmentId;
+                    break;
                 }
```
Comment (krzychu124) [inline TLM/TLM/UI/SubTools/VehicleRestrictionsTool.cs]: So what's the point of update variable now?

Comment (kianzarrin) [reply TLM/TLM/UI/SubTools/VehicleRestrictionsTool.cs]: to break and avoid exception. maybe i should rename it to updated

Comment (krzychu124) [reply TLM/TLM/UI/SubTools/VehicleRestrictionsTool.cs]: I'm asking because you've removed `RefreshCurrentRestrictedSegmentIds` located few lines below. Maybe I don't understand what is going on here, but I don't know how this little change (break) is preventing exception. Not to mention that `RefreshCurrentRestrictedSegmentIds` in this method(`ShowSigns`) was always(if `updatedSegmentId` changed) called **after** iteration

Comment (kianzarrin) [reply TLM/TLM/UI/SubTools/VehicleRestrictionsTool.cs]: There is no point to delay it anymore. It moved it to earlier point. See the diff at the bottom of the file.

**Comment by kianzarrin** [comment]
This is a small review. why can't I merge it in with one approval?
