### PR TITLE
fix bidirectional zigzag

### LINKED ISSUE #1486: Trains zig zag on bi-directiona tracks
based on: https://github.com/CitiesSkylinesMods/TMPE/pull/1483#issuecomment-1075259163

For each lane transition routing manager calculates distance between similar lane index between the two lanes.
Similar lane index for bidirectional train tracks can flip if you reverse the segment placement.
Therefore,  if you reverse the placement of bidirectional train network, then trains will PREFER to zigzag on middle nodes (to minimize cost of transition) even though all lane transitions will be created. 

image
in the picture I have used 3 bidirectional segments between the two train stations. the middle one is placed at reverse direction. That is why the trains would prefer to zigzag. I also have forced a node in the middle. if you zoom in you notice all lane transitions are created but the preferred transition is the zigzagged one.

in such circumstances:
- for middle nodes, only one transition should be created.
- for other nodes all transitions should be created but the distance should compare inner/outer similar lane index (I think this would work but I have not tested it).

Also we need to look at the code to see if there is any other situations in which we might compare inner/outer similar lane index.

### PR DESCRIPTION
**Pull request by kianzarrin**
fixes #1486
[TMPE.zip](https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=1486-bidirectional-zigzag)

when at least one track is bidirectional I reverse similar lane index if:
- segments are in opposite directions
- XOR only one segment is inverted
- XOR lane directions do not match: 

| dir1   | dir2  | lanes match |
| ------------- | ------------- | ------------- |
| bidirectional  | backward    |  no |
| bidirectional  | forward | yes |
| bidirectional  | bidirectional  | yes |

Additional changes:
- renamed a few variables with regards to direction.
- added a few extension methods.

### CODE REVIEW

**Comment by kianzarrin** [comment]
I converted to draft because I'd like to do some tests

File: TLM/TLM/Manager/Impl/RoutingManager.cs [hunk 1]
```diff
@@ -2342,5 +2346,45 @@ bool laneChangesAllowed
...
+        private bool ShouldReverseSimilarLaneIndex(
+            bool segmentInvert1, NetInfo.Lane laneInfo1, bool startNode1,
+            bool segmentInvert2, NetInfo.Lane laneInfo2, bool startNode2) {
+#if DEBUG
+            bool logRouting = DebugSwitch.Routing.Get(); 
+#else
+            const bool logRouting = false;
+#endif
+            bool both1 = laneInfo1.m_finalDirection == NetInfo.Direction.Both;
+            bool both2 = laneInfo2.m_finalDirection == NetInfo.Direction.Both;
```
Comment (aubergine10) [inline TLM/TLM/Manager/Impl/RoutingManager.cs:2362]: Is there a need here to check the `Avoid` directions in case one of the lanes is on a station track segment?

File: TLM/TLM/GlobalSuppressions.cs [hunk 2]
```diff
@@ -0,0 +1,9 @@
+// This file is used by Code Analysis to maintain SuppressMessage
+// attributes that are applied to this project.
+// Project-level suppressions either have no target or are given
+// a specific target and scoped to a namespace, type, member, etc.
+
+using System.Diagnostics.CodeAnalysis;
+
+[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1117:Parameters should be on same line or separate lines", Justification = "<Pending>", Scope = "member", Target = "~M:TrafficManager.Manager.Impl.RoutingManager.RecalculateLaneEndRoutingData(System.UInt16,System.Int32,System.UInt32,System.Boolean)")]
+[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1117:Parameters should be on same line or separate lines", Justification = "<Pending>", Scope = "member", Target = "~M:TrafficManager.Manager.Impl.RoutingManager.ShouldReverseSimilarLaneIndex(System.Boolean,NetInfo.Lane,System.Boolean,System.Boolean,NetInfo.Lane,System.Boolean)~System.Boolean")]
```
Comment (aubergine10) [inline TLM/TLM/GlobalSuppressions.cs:9]: Can't we just add these suppressions in the file itself?

File: TLM/TLM/Util/TrackUtils.cs [hunk 3]
```diff
@@ -20,11 +20,28 @@ internal static class TrackUtils {
...
+        /// <summary>
+        /// checks if vehicles move backward or bypass backward (considers LHT)
+        /// </summary>
+        /// <returns>true if vehicles move backward including AvoidForward,
+        /// false if vehicles going ward, bi-directional, or non-directional</returns>
+        internal static bool IsGoingBackward(this NetInfo.Lane laneInfo) =>
+            laneInfo.m_finalDirection.IsGoingBackward();
+
+        internal static bool IsGoingForward(this NetInfo.Lane laneInfo) =>
+            laneInfo.m_finalDirection.IsGoingForward();
```
Comment (aubergine10) [inline TLM/TLM/Util/TrackUtils.cs:45]: Would it make more sense to put these in `NetLaneExtensions.cs` ?

While unlikely, there's nothing to stop asset creators from adding the `Avoid` directions to any net lane on any type of network? So this approach to checking direction should be used as standard IMO.

Also, why no xmldoc for the `IsGoingForward` extensions?

File: TLM/TLM/GlobalSuppressions.cs (hunk 2 above)
Comment (kianzarrin) [reply TLM/TLM/GlobalSuppressions.cs:9]: It would be bulky.

File: TLM/TLM/Manager/Impl/RoutingManager.cs (hunk 1 above)
Comment (kianzarrin) [reply TLM/TLM/Manager/Impl/RoutingManager.cs:2362]: station tracks have `AvoidForward`/`AvoidBackward` direction. this means their similar lane index will restart if you look at them from the other side. `AvoidForward` will actually be considered backward in here.

File: TLM/TLM/Util/TrackUtils.cs (hunk 3 above)
Comment (kianzarrin) [reply TLM/TLM/Util/TrackUtils.cs:45]: This is `NetInfo.Lane` though not `NetLane`. I can create a new class. 

> While unlikely, there's nothing to stop asset creators from adding the Avoid directions to any net lane on any type of network?

Defiantly not unlikely. even vanila assets use `AvoidForward`/`AvoidBackward` and I have checked for them here.
Unless if you mean the `Avoid` direction. It would make a the lane symmetrical in both directions (bidirectional) and as the doc suggest I am to return false.

> Also, why no xmldoc for the IsGoingForward extensions?

forgot.

**Comment by kianzarrin** [comment]
I performed several tests involving building/deleting/spliting/reversing segment at junction and did not manage to break lane routing.

**Comment by aubergine10** [comment]
@kianzarrin can you merge latest changes for `master`

**Comment by kianzarrin** [comment]
@Elesbaan70 any opinion on this?

**Comment by kianzarrin** [comment]
> I've spent very little time in the routing manager, so I don't think I have enough prior knowledge of how the code works to be of any use here. 🤷‍♂️

what about you @aubergine10

**Comment by aubergine10** [comment]
@kianzarrin hoping to do some testing in a couple of hours

**Comment by kianzarrin** [comment]
good idea. if someone can't understand the code then at least some testing can be done.

File: TLM/TLM/Manager/Impl/RoutingManager.cs [hunk 4]
```diff
@@ -2342,5 +2346,45 @@ bool laneChangesAllowed
...
+            bool reverse;
+            if (!both1 && !both2) {
+                // both lanes are one-way or station tracks
+                // [https://github.com/CitiesSkylinesMods/TMPE/issues/1486#issuecomment-1075699771] what about station tracks connecting to unidirectional tracks?
+                reverse = false;
+            } else {
+                // at least one lane is non-station bidirectional
+                reverse = startNode1 == startNode2; // if the common node is start node for both segments then they are facing each other and are in opposite direction.
+                reverse ^= segmentInvert1 != segmentInvert2;
+                reverse ^= backward1 != backward2;
```
Comment (krzychu124) [inline TLM/TLM/Manager/Impl/RoutingManager.cs:2375]: Why not the boring if else? This part is almost as unreadable as it was possible to be written.

| P | Q |  `XOR` |
|---|---|---|
|1|1|`0`|
|1|0|`1`|
|0|1|`1`|
|0|0|`0`|

**Review by krzychu124 — APPROVED** [review]

File: TLM/TLM/Manager/Impl/RoutingManager.cs [hunk 5]
```diff
@@ -2342,5 +2346,45 @@ bool laneChangesAllowed
...
+            bool segmentInvert2, NetInfo.Lane laneInfo2, bool startNode2) {
+#if DEBUG
+            bool logRouting = DebugSwitch.Routing.Get(); 
+#else
+            const bool logRouting = false;
+#endif
+            bool both1 = laneInfo1.m_finalDirection == NetInfo.Direction.Both;
+            bool both2 = laneInfo2.m_finalDirection == NetInfo.Direction.Both;
+            bool backward1 = laneInfo1.IsGoingBackward();
+            bool backward2 = laneInfo2.IsGoingBackward();
```
Comment (aubergine10) [inline TLM/TLM/Manager/Impl/RoutingManager.cs:2364]: Move in to `else` block? We don't need to know `backwardN` until we reach the `else` block?

Note: I don't know if the compiled IL will do that optimisation on its own.

File: TLM/TLM/Manager/Impl/RoutingManager.cs (hunk 4 above)
Comment (aubergine10) [reply TLM/TLM/Manager/Impl/RoutingManager.cs:2375]: I prefer the logic operators tbh, much more readable.

Comment (aubergine10) [reply TLM/TLM/Manager/Impl/RoutingManager.cs:2375]: I prefer the logic operators tbh, much more readable.

Comment (kianzarrin) [reply TLM/TLM/Manager/Impl/RoutingManager.cs:2375]: @krzychu124 why is it unreadable?
1-if only `startNode1 == startNode2` => segments are facing each other => need to reverse lane index
2-if only `segmentInvert1 != segmentInvert` => segments are in different directions => need to reverse lane index
3-if only `backward1 != backward2` => lanes are in different directions => need to reverse lane index

if you change direction two times it is as if direction did not changed. so that is why we need xor. its like toggle.
I can put more comments.

> Why not the boring if else?

3 conditions => 9 different branches. not only that it would be slow but also it would not make much sense and it would be unreadable.

Why did you include the truth table for xor? You are thinking too much! You should think of `^=` as toggle operator:
```cs
x ^= true => x = ~x
x ^= false => x = x
```

PS: I admit that this part of the logic is hard to understand. But the again, direction logic is typically supper confusing in CS. luckily I had a lot of experience with this direction madness!

Comment (aubergine10) [inline TLM/TLM/Manager/Impl/RoutingManager.cs:2375]:
```suggestion
                // Reverse if segments are facing each other
                reverse = startNode1 == startNode2; 
                // Reverse if segments are different directions
                reverse ^= segmentInvert1 != segmentInvert2;
                // Reverse if lanes are in different directions
                reverse ^= backward1 != backward2;
```

Comment (aubergine10) [reply TLM/TLM/Manager/Impl/RoutingManager.cs:2375]: Just add some code comment? See my suggested change below.

File: TLM/TLM/Manager/Impl/RoutingManager.cs (hunk 5 above)
Comment (kianzarrin) [reply TLM/TLM/Manager/Impl/RoutingManager.cs:2364]: it would be useful for the log.
If you look at the rest of the code in routing manager, the scope of the variables is increased for the sake of debug log.
at the cost of a bit of performance. but this code is not that performance critical so its fine (performance matters but only in terms of reducing loading time).

File: TLM/TLM/Manager/Impl/RoutingManager.cs (hunk 4 above)
Comment (kianzarrin) [reply TLM/TLM/Manager/Impl/RoutingManager.cs:2375]: good idea.

File: TLM/TLM/GlobalSuppressions.cs (hunk 2 above)
Comment (kianzarrin) [reply TLM/TLM/GlobalSuppressions.cs:9]: I will do this for the sake of consistency with the rest of TMPE

File: TLM/TLM/Manager/Impl/RoutingManager.cs (hunk 4 above)
Comment (kianzarrin) [reply TLM/TLM/Manager/Impl/RoutingManager.cs]: is it better now?

**Review by aubergine10 — APPROVED** [review]
Tested in-game and everything seems to be working fine.

I have very few bidirectional tracks, most of my rail network is normal tracks. Note that I'm not currently using any single track networks so didn't test that or interoperability with Single Train Track AI.
