### PR TITLE
Auto-debug ExtCitizenInstanceManager.StartPathFind()

### LINKED ISSUE #840: Bug in StartPathFind() when building not present
This issue was reported by ninja in #825 (but wasn't specifically related to that issue hence opening this one).

```
Error: System.NullReferenceException: Object reference not set to an instance of an object
at TrafficManager.Manager.Impl.ExtCitizenInstanceManager.StartPathFind (uint16,CitizenInstance+,TrafficManager.API.Traffic.Data.ExtCitizenInstance+,TrafficManager.API.Traffic.Data.ExtCitizen+,UnityEngine.Vector3,UnityEngine.Vector3,VehicleInfo,bool,bool) <0x00c16>
at TrafficManager.Custom.AI.CustomCitizenAI.CustomStartPathFind 
```

References to more info:

* [savegame](https://steamcommunity.com/sharedfiles/filedetails/?id=2057580865)
* [logs](https://github.com/CitiesSkylinesMods/TMPE/issues/825#issuecomment-612603594)

krzychu [narrowed down the problem](https://github.com/CitiesSkylinesMods/TMPE/issues/825#issuecomment-612674958):
debugger

And specified a fix in https://github.com/CitiesSkylinesMods/TMPE/pull/834#pullrequestreview-392440336

### PR DESCRIPTION
**Pull request by aubergine10**
Fixes #840

If an exception occurs in `StartPathFind()` we don't get much information in the logs to help us determine what specifically caused it.

This commit tries to remedy that by intercepting the exception, then repeating the `StartPathFind()` only this time with full debug logging. The original exception is then rethrown.

The only performance overheads during normal operation should be:

* Adding a token to the stack for the `try .. catch`
* An additional method call, that will likely be inlined by the jitter
* Setting two bools `true|false` on each invocation (previously they were `const` and `false` in `RELEASE` builds.)
* A bunch of conditional checks (eg. `if (logParkingAi) { ... }`), one for each log call
    * Due to branching in `InternalStartPathFind()` only a few will be encountered.
    * I assume branch predication will quickly optimise things for nromal operation

Hopefully the performance impacts will be negligible, but that remains to be tested.

This PR is result of by Nijamods (ninjanoobslayer) issue report in https://github.com/CitiesSkylinesMods/TMPE/issues/825#issuecomment-612538582 and subsequent log files in https://github.com/CitiesSkylinesMods/TMPE/issues/825#issuecomment-612545514 . I've sent a build of TMPE with this modification to Ninja to test so we should know if it works with followup in #825.

### CODE REVIEW

**Comment by aubergine10** [comment]
Actually, I can just repeat the call to the internal method to debug the specific params that caused the error... update incoming...

**Comment by aubergine10** [comment]
I've updated this so now it does the logging on each occurrence of the error, simplifying state management in the process. User has to click on-screen error box anyway so they won't be caring about split second it takes to do the full debug log.

File: TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs [hunk 1]
```diff
@@ -942,7 +998,7 @@ > ItemClass.Service.Office
                 CitizenInstance.Flags.None;
```
Comment (krzychu124) [inline TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs:999]: https://github.com/CitiesSkylinesMods/TMPE/blob/c3137d6d1f252a852aa4097f9e85c9b713322343/TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs#L966-L967
replace with
```cs
 if (allowRandomParking && instanceData.m_targetBuilding != 0 && 
    (buildingsBuffer[instanceData.m_targetBuilding].Info &&
     buildingsBuffer[instanceData.m_targetBuilding].Info.m_class.m_service
```
That change will fix possible `NullReferenceException` from #825 (user report)
_I don't think that fixing null ref will solve Stuck cims issue :/_

Comment (aubergine10) [reply TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs:999]: @krzychu124 I've spaced it out a bit but does this look correct:

```cs
            if (extVehicleType == ExtVehicleType.PassengerCar ||
                extVehicleType == ExtVehicleType.Bicycle) {

                if (allowRandomParking
                    && instanceData.m_targetBuilding != 0
                    && buildingsBuffer[instanceData.m_targetBuilding].Info != null
                    && (
                        buildingsBuffer[instanceData.m_targetBuilding].Info.m_class.m_service > ItemClass.Service.Office
                        || (instanceData.m_flags & CitizenInstance.Flags.TargetIsNode) != 0
                       )
                    )
                {

                    randomParking = true;
                }
            }
```

Comment (krzychu124) [reply TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs:999]: The key here is to not comparing `MonoBehaviour` with `null`, because it may return false positive result when object was destroyed in the same frame (not bad, pretty rare situation, we will get one exception only xD ).
More info about null thingies: https://blogs.unity3d.com/2014/05/16/custom-operator-should-we-keep-it/

Comment (aubergine10) [reply TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs:999]: So this:

`buildingsBuffer[instanceData.m_targetBuilding].Info != null`

should be just:

`buildingsBuffer[instanceData.m_targetBuilding].Info`

?

Comment (krzychu124) [reply TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs:999]: Yeah, I know it looks weird, but I think that should cover all cases

Comment (aubergine10) [reply TLM/TLM/Manager/Impl/ExtCitizenInstanceManager.cs:1006]: Updated

**Comment by aubergine10** [comment]
@krzychu124 is this ok for merge?
