### PR TITLE
Bugfix floating vehicles when Parking AI disabled

### LINKED ISSUE #846: Parking cars exhibit odd behaviors
### Describe the problem

When cars are trying to park they will go through buildings, through fields, fly through the air to get to a parking spot. This occurs on roads that have parking spots and also on parking lots. I do use parking lots quite a bit so not sure if that's an issue; however, with it also affecting vanilla roads with parking, my parking lots may not be a problem. I have not started a new city with my mods turned off, but i've been using TM:PE for over 18 months now and I never saw this behavior until the Sunset Harbor release. I am not using Industries or Sunset Harbor DLCs at this time.

Update, so I turned off TM:PE and loaded my save and I am not seeing the same behavior. I should've done that from the start.  Perhaps it's the parking AI? Idk. Thanks for looking into this!!

### Steps to reproduce

1. Load my city 
2. Just play and watch areas where cars are trying to park on streets. 
3. Cars will float into opposite lanes of traffic, they will block intersections, they will go through open areas and go under or over ground.

### Log files

Attaching output log and tmpe.log

### Savegame?

https://steamcommunity.com/sharedfiles/filedetails/?id=2063426783

### Screenshots?

Did not take any but the save game should show what I'm talking about, if more info is needed like screenshots or videos I can supply.
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/4489425/TMPE.log)
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/4489426/output_log.txt)

### PR DESCRIPTION
**Pull request by krzychu124**
- fixed floating vehicles if ParkingAI disabled
- if parkingAI is disabled, mod use vanilla code but preserve parking restrictions

**Latest build of this PR is available** [here](https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=disabled-parking-ai--vehicles-floating-fix)

Closes #846

### CODE REVIEW

**Review by thebugfixnet — APPROVED** [review]
Code looks good. Works also well ingame. 

Vehicles not floating and parking restrictions are recognized.

**Comment by krzychu124** [comment]
@kianzarrin wanna test it or I can merge it? I spent numerous hours to find the cause, Biffa is using this version for about 2 weeks(branded as `Preview`) 😅

**Comment by kianzarrin** [comment]
I don't understand the problem or the code. there is a long list of comments in the issue. can you please explain in summary why the cars were floating?

and what does your code do? it seems to do more than just calling vanilla parking. is this a hackish fix? does this mean TMPE realistic parking algorithm is bypassed? do the buildings get red if there is not enough parking nearby? what should I expect in the test result?

File: TLM/TLM/Manager/Impl/AdvancedParkingManager.cs [hunk 1]
```diff
@@ -2896,6 +2896,50 @@ bool citizenDebug
...
+                                                       segment,
+                                                       width,
+                                                       length,
+                                                       out parkPos,
+                                                       out parkRot,
+                                                       out parkOffset)) {
+                return false;
+            }
+
+            // in vanilla parkOffset is always >= 0 for RoadSideParkingSpace
```
Comment (kianzarrin) [inline TLM/TLM/Manager/Impl/AdvancedParkingManager.cs:2922]: code readability issue:
if this is true, shouldn't this be an assertion? maybe LogError in else clause?
what will happen if `parkOffset  < 0 ` is passed to `GetClosestLanePosition()`? is it really necessary to check?

**Review by kianzarrin — CHANGES_REQUESTED** [review]

File: TLM/TLM/Manager/Impl/AdvancedParkingManager.cs (hunk 1 above)
Comment (krzychu124) [reply TLM/TLM/Manager/Impl/AdvancedParkingManager.cs:2922]: @kianzarrin 
That test is crucial because when vanilla code(called via reverse redirection) returns `-1` it means that parking space is inside of a building(residental building parking spot or parking building).
`Parking offset` is just segment offset on the parking lane and since we can only restrict roadside parking spaces we need to know that. 
`GetClosestLanePosition()` is pretty expensive compared to other methods so it's good to skip it if we know we won't need tests for parking lane.

**Comment by krzychu124** [comment]
Quick summary where was the bug.

When `ParkingAI` was disabled and Cim was about to park his vehicle, he was still using custom `ParkingAI` logic to search for parking spot which usually involve additional `PF` calls (few times wider range of search).
Disabled `ParkingAI` also meant that all code responsible for triggering additional path finds was inactive. 
Additionally vehicle which gets `Parking` flag(parking spot found and vehicle is at the last position of his path to destination) has ability to drift in straight line to parking spot (commercial/residetial building parking spot) - regular vanilla behaviour.

So it is just vanilla parking search _with **TM:PE** `Parking restrictions` support._

Building colors are based on statistics from **TM:PE** `ParkingAI` (found/not found) - won't work when `ParkingAI` is off, obviously.

File: TLM/TLM/Manager/Impl/AdvancedParkingManager.cs (hunk 1 above)
Comment (kianzarrin) [reply TLM/TLM/Manager/Impl/AdvancedParkingManager.cs:2922]: maybe put a comment that -1 means error.
"always >= 0 " is a bit misleading.

**Review by kianzarrin — APPROVED** [review]
LGTM. restrictions work. cars don't float.

File: TLM/TLM/Manager/Impl/AdvancedParkingManager.cs (hunk 1 above)
Comment (krzychu124) [reply TLM/TLM/Manager/Impl/AdvancedParkingManager.cs:2922]: Let me explain: _(...) always >= 0 **for RoadSideParkingSpace**_ 
It's not an error... Check vanilla, code is pretty straight forward to understand 😉
