### PR TITLE
Fixed recalculation after lane connection remove

### LINKED ISSUE #1198: TMPE connections is not restablished after removing lane connection
> Milestone update: This was partially fixed in v11.6.2 as shown in changelog, but [additional issue was identified](https://github.com/CitiesSkylinesMods/TMPE/issues/1198#issuecomment-1127964194) which will be fixed by #1550 in v11.6.6.0. As such the milestone for this issue has been updated to 11.6.6.0.

I tested TMPE lane connections on Train Network using AR(Adaptive roads) mod and HUT mod(Hide unconnected tracks).
AR gets connections from Routing Manger
HUT gets connections from Lane Connection Manager.

when I create remove the red connection
image
AR shows this : tracks not reconnected which is indicates a bug:
image
HUT shows this : tracks VISUALLY (But not really) reconnected as expected:
image

This means Lane Connection manager rightfully removes the lane connection data but routing manager does not.

To prove that the problem is with TMPE and not with AR I tested it with train stops:
image
in the picture above I cannot make a stop which means even though I removed the lane connection, The tracks did not get reconnected.

Note: If I force node update using MoveIT or if I create another lane connection on another segment, the track data will update correctly.

Note2: when I add lane connection on train tracks, I notice in the log that LaneArrowManger is updated. but when I remove tracks LaneArrowManager is not updated. I am not sure if LaneArrowManager is relevant for train networks or if this is somehow relevant.

Need: routing manager should reconnect tracks after I remove lane connection

### PR DESCRIPTION
**Pull request by krzychu124**
- fixed recalculation after lane connection removal, 
- refactored `RequestRecalculation(segmentId, propagate)`

Closes #1198

### CODE REVIEW

File: TLM/TLM/Manager/Impl/RoutingManager.cs [hunk 1]
```diff
@@ -167,24 +167,21 @@ public class RoutingManager
...
-                    }
+                RequestNodeRecalculation(ref endNode);
+            }
+        }
+
+        public void RequestNodeRecalculation(ref NetNode node) {
+            for (int i = 0; i < 8; ++i) {
+                ushort otherSegmentId = node.GetSegment(i);
+                if (otherSegmentId != 0) {
+                    RequestRecalculation(otherSegmentId, false);
```
Comment (kianzarrin) [inline TLM/TLM/Manager/Impl/RoutingManager.cs:184]: why not just segmentId?

**Review by kianzarrin — APPROVED** [review]
Cool!

**Review by DaEgi01 — APPROVED** [review]

**Comment by kianzarrin** [comment]
its working! 
image

File: TLM/TLM/Manager/Impl/RoutingManager.cs (hunk 1 above)
Comment (krzychu124) [reply TLM/TLM/Manager/Impl/RoutingManager.cs:184]: copy-paste 😄 I'll change 😉

Comment (krzychu124) [reply TLM/TLM/Manager/Impl/RoutingManager.cs]: Changed!

**Review by DaEgi01 — COMMENTED** [review]
soooo sexy
