### PR TITLE
Careful updating of tooltips; Correct reset of timed TL UI

### LINKED ISSUE #861: Timed Traffic Light tool not properly cleaned up on close
### Describe the problem
Timed Traffic lights UI breaks when user closing UI or selecting other tool without unselecting node first.

### Steps to reproduce

1. Set up simple TTL at any intersection you want
2. You can start TTL sequence but not required
3. Hit close tool (Esc) or change tool to other one
4. Enable TTL tool again (breaks UI - screenshot below)

### Log files

```cs
Error 851.9354609: TimedTrafficLightsTool._guiTimedControlPanel: System.ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
  at System.Collections.Generic.List`1[System.UInt16].get_Item (Int32 index) [0x00000] in <filename unknown>:0 
  at TrafficManager.UI.SubTools.TimedTrafficLights.TimedTrafficLightsTool.GuiTimedControlPanel (Int32 num) [0x00000] in <filename unknown>:0 
   at CSUtil.Commons.Log.LogToFile(System.String log, LogLevel level)
   at CSUtil.Commons.Log.Error(System.String s)
   at TrafficManager.UI.SubTools.TimedTrafficLights.TimedTrafficLightsTool.GuiTimedControlPanel(Int32 num)
   at UnityEngine.GUILayout+LayoutedWindow.DoWindow(Int32 windowID)
   at UnityEngine.GUI.CallWindowDelegate(UnityEngine.WindowFunction func, Int32 id, Int32 instanceID, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
```

### Savegame?
Not necessary, UI always breaks 

### Screenshots?

image

### Notes
Tested on **TM:PE 11.4.0:FullDebug-master**, works on **11.2.x** 

When UI became broken, **RightClick** anywhere to reset internal node selection then all should start work correctly

### LINKED ISSUE #879: Refreshing Slider tooltip text may cause CTD during savegame loading process
### Describe the problem
Recent changed to UISlider tooltip value refresh action may cause CTD when game is loading saved game.

### Steps to reproduce

I'm not 100% sure how to reproduce it, but I might be triggered when a slider value was set to different value than default, and stored in savegame during save game process.

### Log files
```cs
========== OUTPUTING STACK TRACE ==================

  ERROR: SymGetSymFromAddr64, GetLastError: 'Próbowano uzyskać dostęp do nieprawidłowego adresu.' (Address: 00007FF7A3756668)
0x00007FF7A3756668 (Cities) 
  ERROR: SymGetSymFromAddr64, GetLastError: 'Próbowano uzyskać dostęp do nieprawidłowego adresu.' (Address: 00007FF7A3756DF6)
0x00007FF7A3756DF6 (Cities) 
  ERROR: SymGetSymFromAddr64, GetLastError: 'Próbowano uzyskać dostęp do nieprawidłowego adresu.' (Address: 00007FF7A3794DB3)
0x00007FF7A3794DB3 (Cities) 
0x00000000B6CB3D59 (Mono JIT Code) (wrapper managed-to-native) UnityEngine.Font:RequestCharactersInTexture (string,int,UnityEngine.FontStyle)
0x00000000B6CB397A (Mono JIT Code) ColossalFramework.UI.UIDynamicFont:RequestCharacters (string,int,UnityEngine.FontStyle)
0x00000000B6CB3161 (Mono JIT Code) ColossalFramework.UI.UIDynamicFont/DynamicFontRenderer:MeasureString (string)
0x00000000B6CC2AFA (Mono JIT Code) ColossalFramework.UI.UILabel:GetVertAlignOffset (ColossalFramework.UI.UIFontRenderer)
0x00000000B6CC04D5 (Mono JIT Code) ColossalFramework.UI.UILabel:ObtainRenderer ()
0x00000000B6CBE0E8 (Mono JIT Code) ColossalFramework.UI.UILabel:Invalidate ()
0x00000000B6CDA907 (Mono JIT Code) ColossalFramework.UI.UILabel:OnTextChanged ()
0x00000000B6CD0773 (Mono JIT Code) ColossalFramework.UI.UILabel:set_text (string)
0x00000001F440802B (Mono JIT Code) ColossalFramework.UI.UIComponent:RefreshTooltip ()
0x00000001F440797C (Mono JIT Code) TrafficManager.State.OptionsGameplayTab:OnAltLaneSelectionRatioChanged (single)
0x00000001F4407CB8 (Mono JIT Code) (wrapper delegate-invoke) ICities.OnValueChanged:invoke_void__this___single (single)
0x00000001F44075A7 (Mono JIT Code) UIHelper/<AddSlider>c__AnonStorey1:<>m__0 (ColossalFramework.UI.UIComponent,single)
0x00000000B6D5E33B (Mono JIT Code) ColossalFramework.UI.UISlider:OnValueChanged ()
0x00000000B6D5E105 (Mono JIT Code) ColossalFramework.UI.UISlider:set_value (single)
0x00000001F44073D3 (Mono JIT Code) TrafficManager.State.OptionsGameplayTab:SetDLSPercentage (byte)
0x00000001F43EFAF6 (Mono JIT Code) TrafficManager.Manager.Impl.OptionsManager:LoadData (byte[])
0x00000001F439E4AB (Mono JIT Code) TrafficManager.State.SerializableDataExtension:OnLoadData ()
0x00000001F439D397 (Mono JIT Code) SerializableDataWrapper:OnLoadData ()
0x00000001F439CEB0 (Mono JIT Code) SimulationManager:LateUpdateData (SimulationManager/UpdateMode,single,single)
0x00000001F4393DAC (Mono JIT Code) SimulationManager:Managers_LateUpdateData (SimulationManager/UpdateMode,single,single)
0x00000000501C2A0F (Mono JIT Code) LoadingManager/<LoadSimulationData>c__IteratorB:MoveNext ()
0x00000000501C0DF0 (Mono JIT Code) AsyncTask:Execute ()
0x0000000021A9D635 (Mono JIT Code) SimulationManager:SimulationStep ()
0x0000000021A22D1A (Mono JIT Code) SimulationManager:SimulationThread ()
0x00000000061CE352 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
0x00007FF82701AE98 (mono) mono_walk_stack
0x00007FF826F78A89 (mono) mono_runtime_invoke
0x00007FF826F9E36D (mono) mono_unity_thread_fast_detach
0x00007FF8270A8218 (mono) unity_mono_reflection_method_get_method
0x00007FF866376FD4 (KERNEL32) BaseThreadInitThunk
0x00007FF86681CEC1 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

**** Crash! ****
```

### Notes or questions?
`UnityEngine.Font:RequestCharactersInTexture` shouldn't ever be called from thread other than `Main/UI`. Above stacktrace shows that it was called from async loop of `Simulation` Thread

### PR DESCRIPTION
**Pull request by kvakvs**
Fixes #879 UI sliders are not force-refreshed if the game is not loaded (causes hard crash)
Fixes #861 Closing timed TL UI is now correctly reset upon reentering timed TL UI

### CODE REVIEW

File: TLM/TLM/State/OptionsTabs/OptionsGeneralTab.cs [hunk 1]
```diff
@@ -243,7 +243,9 @@ public static class OptionsGeneralTab {
                 = string.Format(
                     T("General.Tooltip.Format:Window transparency: {0}%"),
                     GlobalConfig.Instance.Main.GuiOpacity);
-            _guiOpacitySlider.RefreshTooltip();
+            if (LoadingExtension.IsGameLoaded) {
```
Comment (aubergine10) [inline TLM/TLM/State/OptionsTabs/OptionsGeneralTab.cs:246]: How does this solve issue of the update happening in _wrong thread_?

Comment (kvakvs) [reply TLM/TLM/State/OptionsTabs/OptionsGeneralTab.cs:246]: While loading the savegame, slider values are set via this setter, the condition prevents the GUI update from executing which solves the hard crash. A more elegant way would be to move GUI update out of these functions.
