### PR TITLE
Lane routing tools now support onscreen display

### LINKED ISSUE #587: Shortcut keys standardisation
I've just added a page to the wiki listing _some_ of the shortcut keys:

https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Shortcuts

I'd like to propose the following standardisation:

* **`Shift`** - replicate something (between junctions, along a route, ~~around a node~~)
* **`Ctrl`** - Should give more control
    * Example: Speed Limits tool - `Ctrl` toggles between direction vs. lanes
* **`Alt`** - Delivers alternative to the standard functionality
    * Example: Lane Arrows tool - Alt-clicking applies turning lane, rather than selecting the lane for manual customisation
* **`Del`** - Should delete stuff (for whatever is currently selected)
    * Example: Lane Connector tool - `Del` deletes all connectors for selected node

cc: @kvakvs @kianzarrin

### LINKED ISSUE #830: 1.13.0 lane connector does not highlight nodes correctly on-hover
### Description

Using TM:PE LABS 1.13.0, nodes do not highlight properly on the lane connector.

### Reproduction steps

1. Open lane connector.
2. Hover over any node.

### Screenshots

screenie

In the above screenshot, I am actively hovering the cursor over the left node. The cursor cannot be seen due to screenshot method, however the cursor behaves as-expected. The node lines inside change colour, however the node marker does not. The right node appears normally. It does not change colour when I hover over it either.

### PR DESCRIPTION
**Pull request by kvakvs**
Fixes #830
Fixes #587

bild

bild
bild

# Changes

* Added new interface to be supported by both `LegacySubTool` and new style `TrafficManagerSubTool` which requests keybinds for the current mode
* Lane Connectors tool now suggests Ctrl+S keybind for stay in lane, and cancel rclick/esc.
* Nodes are back to 0.4 alpha (bug: white nodes #830) and hover has alpha too
* Code style changes

### CODE REVIEW

**Comment by kvakvs** [comment]
One UX question 

* Right click in the initial tool mode deactivates the tool (LaneArrows tool in my implementation)
* Or right click does nothing and you remain with the tool active? (all other tools)

I feel like my approach is less intrusive and its easier to leave tools by right clicking. But its not consistent with the other tools. If you agree that leaving tools with right click should be that easy, i'll add that cancel right click into every tool.

**Comment by aubergine10** [comment]
I like right-click to exit tool, but some users might find it confusing/annoying (especially if they have dodgey mouse button like lots of old logitech mice do).

IMO it would be great if all tools could allow right-clicking out of them, but maybe mod option to toggle whether tools can be exited with right click to keep users happy?

It would be great if we could get "most" of the tools updated with OSD and right-click exit for the 11.5.0 release.

The traffic light tools would have to wait probably, but stuff like speed limits, parking restrictions, vehicle restrictions, priority signs, junction restrictions, lane arrows/connectors... I don't know how much work it is per tool? Maybe we release 11.5.0 with just a couple of tools done, then 11.5.x releases update more tools? what do you think?

**Comment by aubergine10** [comment]
Also, is there a way - for lane connectors in particular - to make the right-click text even more specific to current selection mode?

- Exit tool (when nothing selected)
- Exit node (when node selected)
- Exit lane (when lane selected)

**Comment by kvakvs** [comment]
It is not much work, 1-3 hours per tool.
For smarter exit messages we can do for sure, just did not want to grow the translation keys pool and used a generic cancel message.

**Comment by aubergine10** [comment]
I think the strings could be re-used for those translation keys.

For example, 'exit node' could be used on junction restrictions, lane connectors, priority signs...

I think there might only be like 4 possible exit values - those three listed above, and also `Exit segment` (eg. for vehicle restrictions, lane arrows, etc).

**Comment by aubergine10** [comment]
@kianzarrin is there any way to determine if auto-lane connector (Ctrl+S) has multiple states for selected node? for example, could the tooltip indicate _when_ user can repeat the shortcut?

For example, on a basic node on 2 way road, the tooltip could be:

> `Ctrl + S` Auto-connect lanes (repeat for alternate connections)

On a one way road it might be just:

> `Ctrl + S` Auto-connect lanes (repeat to toggle connections)

**Comment by kianzarrin** [comment]
> Right click in the initial tool mode deactivates the tool (LaneArrows tool in my implementation)

Why would that be useful?

**Comment by kianzarrin** [comment]
> On a one way road it might be just:
Ctrl + S Auto-connect lanes (repeat to toggle connections)

@aubergine10  the code is :
```
stayInLaneMode = !oneway ? StayInLaneMode.Both : StayInLaneMode.Forward;
```
So yes something like that. Although if there is only one lane in the backward direction that can stiil be confusing to the user.

File: TLM/TLM/UI/LegacySubTool.cs [hunk 1]
```diff
@@ -24,29 +24,32 @@ public abstract class LegacySubTool {
         private Texture2D windowTexture_;
 
         protected GUIStyle WindowStyle =>
-            windowStyle_ ?? (windowStyle_ = new GUIStyle {
+            // ReSharper disable once ConvertToNullCoalescingCompoundAssignment
+            windowStyle_ ??
+            (windowStyle_
+                 = new GUIStyle {
                                     normal = {
```
Comment (kianzarrin) [inline TLM/TLM/UI/LegacySubTool.cs:31]: wow! what is happening to the indent spaces in here? if you like it would be nice to reduce the indent.

File: TLM/TLM/UI/SubTools/LaneConnectorTool.cs [hunk 2]
```diff
@@ -13,22 +13,28 @@ namespace TrafficManager.UI.SubTools {
...
     using TrafficManager.Util;
     using TrafficManager.UI.Helpers;
+    using TrafficManager.UI.MainMenu;
     using static TrafficManager.Util.Shortcuts;
-    using System;
-    using GenericGameBridge.Service;
 
-    public class LaneConnectorTool : LegacySubTool {
+    public class LaneConnectorTool
+        : LegacySubTool,
```
Comment (kianzarrin) [inline TLM/TLM/UI/SubTools/LaneConnectorTool.cs:20]: why is this still legacy subtool. is it going to be legacy forever. in that case legacy is a misleading name. I suggest to at least change its documentation.

File: TLM/TLM/UI/SubTools/LaneConnectorTool.cs [hunk 3]
```diff
@@ -948,6 +965,7 @@ public LaneConnectorTool(TrafficManagerTool mainTool)
             hoveredLaneEnd = null;
             stayInLaneMode = StayInLaneMode.None;
             RefreshCurrentNodeMarkers();
+            MainTool.RequestOnscreenDisplayUpdate();
```
Comment (kianzarrin) [inline TLM/TLM/UI/SubTools/LaneConnectorTool.cs:968]: if you have to call MainTool.RequestOnscreenDisplayUpdate() in so many places its a sign of badly organized code and also increases the likelyhood of human error. would it help if you do one of the following: 
- use `try{ ... }finally {MainTool.RequestOnscreenDisplayUpdate() }` 
- override `OnToolUpdate()` and do it in every `OnToolUpdate()` call.
-  do it in TrafficManagerTool.OnToolUpdate() in response to click event 
- do it in OnToolGUI in response to any  mouse/key up/down event.

File: TLM/TLM/UI/SubTools/LaneConnectorTool.cs [hunk 4]
```diff
@@ -1040,14 +1062,15 @@ public LaneConnectorTool(TrafficManagerTool mainTool)
...
-                            out bool isTarget,
-                            out Vector3? pos)) {
+                            segmentId: segmentId,
+                            startNode: startNode,
+                            laneIndex: laneIndex,
+                            laneId: laneId,
+                            laneInfo: laneInfo,
+                            outgoing: out bool isSource,
+                            incoming: out bool isTarget,
+                            pos: out Vector3? pos))
```
Comment (kianzarrin) [inline TLM/TLM/UI/SubTools/LaneConnectorTool.cs:1072]: a big chunk of changes in this PR is auto code cleanup changes in places where you have not made any other modifications. in future PR is it possible to do it in two commits (one commit for auto code cleanup and another for the functional changes to the code). I am not sure if its practical because you do not know in advance which files you are going to modify.

I am thinking who is the one to speak! in my own PR's my commits are a big mess!

File: TLM/TLM/UI/LegacySubTool.cs (hunk 1 above)
Comment (kvakvs) [reply TLM/TLM/UI/LegacySubTool.cs:31]: Rider IDE was suggesting to use new language feature, so i had to add a suppress comment. Once the feature is in the supported features, we can apply that suggestion. Also formatted it on several lines otherwise it shoots off screen.

File: TLM/TLM/UI/SubTools/LaneConnectorTool.cs (hunk 2 above)
Comment (kvakvs) [reply TLM/TLM/UI/SubTools/LaneConnectorTool.cs:20]: It is still legacy subtool because i tried to do very few changes. If i upgrade this to new subtool style, this would be a totally different and much larger PR.

File: TLM/TLM/UI/SubTools/LaneConnectorTool.cs (hunk 3 above)
Comment (kvakvs) [reply TLM/TLM/UI/SubTools/LaneConnectorTool.cs:968]: There aren't clear transition changes in legacy subtools, so i have to hunt each one down.
When the tool is upgraded, the update calls will only be located in state change handlers.
Yes the legacy code is badly organized and is very prone to errors that's why it is renamed to legacy and marked obsolete.
No i am not doing this outside in OnToolUpdate or OnToolGUI, that happens every frame.

File: TLM/TLM/UI/SubTools/LaneConnectorTool.cs (hunk 4 above)
Comment (kvakvs) [reply TLM/TLM/UI/SubTools/LaneConnectorTool.cs:1072]: I'm touching things i visit, not everything, and the changes are not too many i hope.
Just scroll through them :)

File: TLM/TLM/UI/SubTools/LaneConnectorTool.cs (hunk 3 above)
Comment (kianzarrin) [reply TLM/TLM/UI/SubTools/LaneConnectorTool.cs:968]: there is no harm done if you call `RequestOnscreenDisplayUpdate()` too many times is there?

Comment (kianzarrin) [reply TLM/TLM/UI/SubTools/LaneConnectorTool.cs:968]: I mean in response to any user event so that it does not reduce FPS.

**Comment by kvakvs** [comment]
> Can you make + and | white like you did in lane arrow tool?

It comes from keybind code as a string, so this will need splitting into separate words and then labels need to be created of each colour. Possible but tedious.

File: TLM/TLM/UI/SubTools/LaneConnectorTool.cs (hunk 3 above)
Comment (kvakvs) [reply TLM/TLM/UI/SubTools/LaneConnectorTool.cs:968]: It will reduce FPS. Every time you call update it clears the hint panel and fills new labels for help, and also resizes the main menu and all labels in it.

Comment (aubergine10) [reply TLM/TLM/UI/SubTools/LaneConnectorTool.cs:968]: I think full refactoring can come later, maybe as a v11.6.0 task? There's already lots of changes in 11.5.0 for users to test.

**Comment by kvakvs** [comment]
@kianzarrin I am now making `|` for dual shortcuts to be white.
I would prefer + to be orange as it is a part of one shortcut and it works together, and for that i should probably revert + in `Alt + Click` shortcuts to also be orange.

**Comment by aubergine10** [comment]
If anyone knows about coloring text it will likely be @Klyte45 as he's done all kinds of UI stuff in his TLM and other mods.

**Comment by klyte45** [comment]
The UILabel class (and some other text components) have a bool `processMarkup`. When enabled, it will process some tags:

<Color #rrggbb>text</color>
<Sprite spriteName> (requires atlas property to be setted)
<Setting settingName> (retrieve value from settings file)

Only color requires close tag. Also colors tags can be stacked. See more details at UIDynamicFontRenderer on ColossalFramework.UI namespace.

(May something in this text can be not so accurate, I wrote this from my memory =V)

File: TLM/TLM/UI/SubTools/LaneArrows/LaneArrowTool.cs [hunk 5]
```diff
@@ -422,40 +423,45 @@ public LaneArrowTool(TrafficManagerTool mainTool)
         /// </summary>
         void IOnscreenDisplayProvider.UpdateOnscreenDisplayPanel() {
             if (fsm_ == null) {
-                OnScreenDisplay.Clear();
+                OnscreenDisplay.Clear();
```
Comment (aubergine10) [inline TLM/TLM/UI/SubTools/LaneArrows/LaneArrowTool.cs:426]: `OnscreenDisplay.Clear()` appears to always be called in this method; would it be worth separating it out of this `if` statement, so:

```cs
void IOnscreenDisplayProvider.UpdateOnscreenDisplayPanel() {
    OnscreenDisplay.Clear();

    if (fsm_ == null) {
        return;
    }

    ...
}
```

The `OnscreenDisplay.Clear()` at end of mehtod could then also be removed?

File: TLM/TLM/UI/MainMenu/OSD/OsdKeybindItem.cs [hunk 6]
```diff
@@ -0,0 +1,47 @@
+namespace TrafficManager.UI.MainMenu.OSD {
+    using System.Collections.Generic;
+    using System.Text;
+    using TrafficManager.State.Keybinds;
+    using TrafficManager.U;
+    using TrafficManager.U.Autosize;
+    using TrafficManager.U.Label;
+
+    /// <summary>Displays a keybind or dual keybind in the OSD panel.</summary>
+    public class OsdKeybindItem : OsdItem {
```
[the remark this answers is not in the document]
Comment (kvakvs) [reply TLM/TLM/UI/MainMenu/OSD/OsdKeybindItem.cs:10]: This displays a keybind option which has 1 or 2 inputkeys and can be a mouse too.

File: TLM/TLM/UI/MainMenu/OSD/OsdClickItem.cs [hunk 7]
```diff
@@ -0,0 +1,100 @@
...
+    using System.Text;
+    using ColossalFramework;
+    using ColossalFramework.UI;
+    using TrafficManager.State.Keybinds;
+    using TrafficManager.U;
+    using TrafficManager.U.Autosize;
+    using TrafficManager.U.Label;
+
+    /// <summary>Displays a mouse click shortcut in OSD panel.</summary>
+    public class OsdClickItem : OsdItem {
```
[the remark this answers is not in the document]
Comment (kvakvs) [reply TLM/TLM/UI/MainMenu/OSD/OsdClickItem.cs:13]: This displays a hardcoded click with modifier keys, not a keybind.
OsdMouse can be an OK name.

File: TLM/TLM/UI/SubTools/LaneArrows/LaneArrowTool.cs (hunk 5 above)
Comment (kvakvs) [reply TLM/TLM/UI/SubTools/LaneArrows/LaneArrowTool.cs:426]: This should only be called if fsm is null (no tool mode active) or if state does not have onscreen hints. I do not want to call it for modes where the modes have hints, it hides the keybinds panel and invalidates it just to show it again in the next line.

File: TLM/TLM/UI/MainMenu/OSD/OsdClickItem.cs (hunk 7 above)
[the remark this answers is not in the document]
Comment (kvakvs) [reply TLM/TLM/UI/MainMenu/OSD/OsdClickItem.cs:13]: Renaming to `HardcodedMouseShortcut` this is only to display shortcuts which are hardcoded and not customizable. And only handles mouse clicks.

File: TLM/TLM/UI/MainMenu/OSD/OsdKeybindItem.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (kvakvs) [reply TLM/TLM/UI/MainMenu/OSD/OsdKeybindItem.cs:10]: Renaming to `Shortcut`.

File: TLM/TLM/UI/MainMenu/OSD/OsdClickItem.cs [hunk 8]
```diff
@@ -0,0 +1,100 @@
...
+            using (UiBuilder<ULabel> labelB = builder.Label<U.Label.ULabel>(text.ToString())) {
+                labelB.Control.processMarkup = true;
+                labelB.ResizeFunction(
+                    r => { r.Stack(mode: UStackMode.NewRowBelow); });
+            }
+        }
+
+        private static string TranslationForMouseButton(UIMouseButton button) {
+            switch (button) {
+                case UIMouseButton.Left:
```
[the remark this answers is not in the document]
Comment (kvakvs) [reply TLM/TLM/UI/MainMenu/OSD/OsdClickItem.cs]: Some games display raw mouse button id, like mouse0, mouse1, ... etc. That is ugly.
The click can be renamed in Crowdin.

File: TLM/TLM/UI/MainMenu/OSD/OsdClickItem.cs [hunk 9]
```diff
@@ -0,0 +1,100 @@
...
+
+        public override void Build(U.UiBuilder<U.Panel.UPanel> builder) {
+            StringBuilder text = new StringBuilder();
+            bool needSeparator = false;
+
+            text.Append($"<color {UConst.SHORTCUT_TEXT_HEX}>");
+
+            if (this.shift_) {
+                text.Append(Translation.Options.Get("Shortcut.Modifier:Shift"));
+                needSeparator = true;
```
[the remark this answers is not in the document]
Comment (kvakvs) [reply TLM/TLM/UI/MainMenu/OSD/OsdClickItem.cs]: Nice! Thanks for the hint :)

File: TLM/TLM/UI/MainMenu/OSD/OsdClickItem.cs [hunk 10]
```diff
@@ -0,0 +1,100 @@
...
+                            string localizedText) {
+            button_ = button;
+            shift_ = shift;
+            ctrl_ = ctrl;
+            alt_ = alt;
+            localizedText_ = localizedText;
+        }
+
+        public override void Build(U.UiBuilder<U.Panel.UPanel> builder) {
+            StringBuilder text = new StringBuilder();
```
[the remark this answers is not in the document]
Comment (kvakvs) [reply TLM/TLM/UI/MainMenu/OSD/OsdClickItem.cs]: Added estimated capacity 9

**Comment by aubergine10** [comment]
The `?` button has no tooltip to explain what it does.

image

Also, would it be worth hiding the `?` button when there are no hints to display?

**Comment by aubergine10** [comment]
These are just random thoughts, I'm trying to picture myself as new user. It is certainly better than what we had before, but I wonder if a new user would fail to grasp that they could just click a segment or node (ie. not apply a shortcut of any kind) to manually edit something?

So, is there merit to including more basic interactions? For example:

image

Imagine being a new user confronted with the scene above. Would would you know that you could just click a segment to edit it's lane arrows?

For that situation, would it be worth adding something like:

> `Click segment` Manually edit the lane arrows

Obviously we don't want to [teach grandma to suck eggs](https://en.wikipedia.org/wiki/Teaching_grandmother_to_suck_eggs), so once a segment is highlighted we wouldn't mention stuff like "Click the buttons to toggle them" because the UI alone is obvious enough.

But when a tool is first opened, and user hasn't selected anything yet, it would perhaps be useful to at least state _what_ they can select. Additionally, maybe an option somewhere to hide the very basic "you can click a node or segment to edit it" type stuff?

**Comment by aubergine10** [comment]
While a lane is selected, the `Ctrl+S` shortcut should be disabled (it should only work when we're in the 'selected node' state):

image

Also, it would be great to tell the user what to actually do once they've selected a lane (as a basic hint mentioned in my last comment), for example...

When they've selected a node:

> `Click incoming lane` Select the lane

When they've clicked incoming lane:

> `Click outgoing lane` Toggle a connection from the incoming lane

**Comment by kvakvs** [comment]
I was thinking about something like current mode description in a separate line and different color (sky blue maybe). I would also like to display those actions you mention in a different way or text colour. Because "click segment" is not actually a keybind or mouse click, its a targeted click action.

Would you like to have that in this PR? Or rather add during the upcoming future PR's?

**Comment by aubergine10** [comment]
We should limit the number of colors shown; maybe yellow for state-specific stuff and brown for multi-state stuff? That stuff (and the 'basic hints' mentioned in my earlier comments) could come in later PRs if desired.

An alternate to things like "Click node or segment" hints would be to revive that stuff you had where the clickable stuff would gently pulse its opacity making it really obvious to user "you can click here to do stuff".

We could probably remove `Escape` shortcut hint - all game tools use that mechanism so users will at least be familiar with that pattern.

For `Delete | Backspace` - do we need to mention both keys? Would stating just one of those keys suffice? For example, on Macs it would be `Backspace`, on other platforms it would be `Delete`. Would help reduce the amount of text.

Another thing I'm thinking - definitely a separate PR at later date - is would there be any merit to introducing some alignment? If you look at boundary between brown and white text, it's jagged which makes it a little difficult to quickly scan with the eyes. Maybe if there was a way to determine longest brown text, then right-align all other brown text to it? That way all the white text would be left-justified; might make it a bit easier to read?

**Comment by kvakvs** [comment]
If you can guarantee that the text will be always 1 line, wrap keys in an invisible panel, and wrap texts in an invisible panel, and make them size to contents, and they'll align nicely.

**Comment by aubergine10** [comment]
I think we will always want to ensure text is short as possible (always one line) so yes, wrapping in panels would work.

**Comment by kvakvs** [comment]
bild
bild

**Comment by aubergine10** [comment]
Another idea for the `?` button: If there are hints, but the hints are hidden, hovering over the button would show the hints.

Use case: I've memorised most of the hints, so have hidden them. Yet one time I'm doing something and I need a recap; I can just hover `?` to see the hints then move away again - no need to toggle them on/off if I just want a quick recap.

**Comment by kvakvs** [comment]
That's possible, but since your mouse is already on the ? just click it.

**Comment by aubergine10** [comment]
Then I have to click again to hide it afterwards.
