### PR TITLE
Avoid null pointer exception in the UIScaler

### LINKED ISSUE #838: Icons not showing up when selecting node after choosing TMPE.
### Steps to reproduce

1.  Select   tmpe, choose the option to change junction yields
2.  Icons don't show up. a
3. 

### Log files

https://gist.github.com/xenoxaos/f0435a8f4cc566c063b08086fc58b2bc

### Savegame?

https://steamcommunity.com/sharedfiles/filedetails/?id=2059435448

### PR DESCRIPTION
**Pull request by kvakvs**
Fixes #838

# Bug

`UIScaler` was using `uiCamera`'s pixel size, while either `UIView.instance` or `UIView.instance.uiCamera` was null. This is now cached and double checked.
Potentially if UI never changes from 1920x1080, we can replace that entire code with a pair of `const`

# Solution

A null check was added for both `UIView.instance` and `UIView.instance.uiCamera`, cached width and height are stored in case those are ever null.
Also: Change to `WorldToScreenPoint` has been reverted as it always been using `Screen.height` not GUI height.

### CODE REVIEW

File: TLM/TLM/U/UIScaler.cs [hunk 1]
```diff
@@ -5,11 +5,46 @@ namespace TrafficManager.U {
...
+        private static float cachedGuiHeight = GUI_HEIGHT;
+
         /// <summary>Screen width for GUI is always fixed at 1920.</summary>
-        public static float GuiWidth => Singleton<UIView>.instance.uiCamera.pixelWidth;
+        public static float GuiWidth {
+            // TODO: Double check if GUI never changes width, the code below can be a const
+            get {
+                UIView uiView = Singleton<UIView>.instance;
+                if (uiView != null) {
+                    Camera uiCamera = uiView.uiCamera;
```
Comment (kianzarrin) [inline TLM/TLM/U/UIScaler.cs:23]: just a minor note.  it would be more compact to write like this:
```c#
UIView uiView = Singleton<UIView>.instance;
Camera uiCamera = uiView?.uiCamera;
if(uiCamera !=null) 
  ...
```

Comment (kvakvs) [reply TLM/TLM/U/UIScaler.cs:23]: But this does not eliminate the null check, in your code null check will happen twice.

Comment (kianzarrin) [reply TLM/TLM/U/UIScaler.cs:23]: yeah its the same code just more compact.

File: TLM/TLM/U/UIScaler.cs [hunk 2]
```diff
@@ -5,11 +5,46 @@ namespace TrafficManager.U {
...
+        /// <summary>Caching because UIView.Instance.uiCamera can be null sometimes.</summary>
+        private static float cachedGuiHeight = GUI_HEIGHT;
+
         /// <summary>Screen width for GUI is always fixed at 1920.</summary>
-        public static float GuiWidth => Singleton<UIView>.instance.uiCamera.pixelWidth;
+        public static float GuiWidth {
+            // TODO: Double check if GUI never changes width, the code below can be a const
+            get {
+                UIView uiView = Singleton<UIView>.instance;
+                if (uiView != null) {
```
Comment (krzychu124) [inline TLM/TLM/U/UIScaler.cs:22]: Wait... that's always true

Comment (kvakvs) [reply TLM/TLM/U/UIScaler.cs:22]: Somehow either uiView or instance was null while rendering overlays, that's what the user reported in #838

Comment (krzychu124) [reply TLM/TLM/U/UIScaler.cs:22]: Ok, I've checked log and nullpointer comes from `Camera` which is `uiCamera` property of `UIView`. 
You've added null check below for that, which should solve problem with exception.

The real problem is why uiCamera was null? Game was already loaded so it seems you tried using old instance, probably destroyed. If you look closely at log you will notice that he loads game multiple times (with exit to main menu)

Comment (kvakvs) [reply TLM/TLM/U/UIScaler.cs:22]: One guess: many users reporting severe overlay rendering artifacts (overlapping with UI) seem to have overlays always enabled in the options. Which might render from the Tool code early before the rest of the UI has finished setting up? Just a guess. Could be true or not.

File: TLM/TLM/U/UIScaler.cs (hunk 1 above)
Comment (aubergine10) [reply TLM/TLM/U/UIScaler.cs:23]: Code compactness is nice, but not at the expense of obscuring clarity of intent of the code.

File: TLM/TLM/U/UIScaler.cs (hunk 2 above)
Comment (kvakvs) [reply TLM/TLM/U/UIScaler.cs:22]: What's my action on this? Can I safely assume instance is always non-null? I'd rather be on the safe side and later would possibly eliminate this class entirely. But now more worried to do minimal changes and solve the crash situation.

Comment (aubergine10) [reply TLM/TLM/U/UIScaler.cs:22]: Be over cautious for now and add an issue to remind more in-depth alterations later?

Comment (krzychu124) [reply TLM/TLM/U/UIScaler.cs:22]: Ok, now I see where is the problem. 
You shouldn't use `Singleton<UIView>` because that way you will create and add new `UIView` each time you call it (everytime with null camera). 
Use `UIView.GetAView()` to get correct `UIView` instance (the main one).
Call to `Singleton.instance` won't work because `UIView` class not extends `Singleton<>` but `MonoBehaviour` directly

**Comment by kvakvs** [comment]
Pushed the suggested change.

**Comment by aubergine10** [comment]
I'll see if this fixes any of the issues I'd been seeing in game.

File: TLM/TLM/U/UIScaler.cs (hunk 2 above)
Comment (kianzarrin) [reply TLM/TLM/U/UIScaler.cs]: Wow! Maybe this is what's causing #822 too!
