### PR TITLE
Destroy UI texture immediately to solve race condition

### LINKED ISSUE #1514: Texture atlas breaks when changing option involving menu rebuild
### Describe the problem
See steps below. Investigating... (TM:PE workshop TEST also affected so probably a bug introduced in texture rebuild fix)

### Steps to reproduce

1. start new game
2. enter options and change PF counter visibility at Maintenance tab
3. close options modal and open TM:PE main menu
4. observe missing textures

Now the fun part
1. enter options once again and revert PF counter visibility setting 
2. close options modal and open TM:PE main menu
3. observe working textures

Now the weird part
1. break textures like in the first step
2. disable one of the features like _Lane Connector_
3. close options and observe menu (working)
4. enable the feature that was changed in step 2.
5. main menu breaks again...

### Screenshots?
image

### Notes or questions?
It looks like every **second** rebuild of _menu, texture source or whatever is happening there_ fixes the problem 🤷‍♂️ 
Everything works, just textures are missing.

### PR DESCRIPTION
**Pull request by krzychu124**
Closes #1514

It turned out that destroying of `MainWindow` is delayed - it destroys also the UI texture atlas because it is not needed anymore.
When new window is created within the same frame it finds the atlas texture that will be destroyed at the end of frame (so it will be `null` after a moment). The first render of new component (in the next frame) check if its atlas is `not null` - otherwise takes default atlas.

I added also a simple `if` condition to rebuild textures with translation only if really needed (language changed).

Build [zip](https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=bugfix/1514-texture-atlas-breaks-on-menu-rebuild)

### CODE REVIEW

File: TLM/TLM/Manager/Impl/OptionsManager.cs [hunk 1]
```diff
@@ -309,7 +309,7 @@ private static void ToSlider(byte[] data, uint idx, ILegacySerializableOption op
         /// Triggers a rebuild of the main menu (toolbar), adding/removing buttons
         /// where applicable, and refreshing all translated text. Very slow.
         /// </summary>
-        internal static void RebuildMenu() {
+        internal static void RebuildMenu(bool reloadTextures = false) {
```
Comment (aubergine10) [inline TLM/TLM/Manager/Impl/OptionsManager.cs:312]: I think this would be better named `languageChanged` as that's more specific to what happened.

Note that the `TMPELifecycle.Instance.TranslationDatabase` methods called later in the method are not texture related. I have no idea why they need treating separately from all the other locale strings.

Comment (aubergine10) [reply TLM/TLM/Manager/Impl/OptionsManager.cs]: Considering there's only 2 calls that set the `bool` to `true` (and they are both in same method - that handles language change) is it worth splitting out that block to separate function as it doesn't really have anything to do with rebuilding main menu.

Comment (krzychu124) [reply TLM/TLM/Manager/Impl/OptionsManager.cs]: True, but now I read the code and I don't see how it works when main game language changes. There is no trigger... 🤷‍♂️

Comment (kvakvs) [reply TLM/TLM/Manager/Impl/OptionsManager.cs]: `KeybindSettingsBase:OnLocaleChanged` is this something of interest?

Comment (krzychu124) [reply TLM/TLM/Manager/Impl/OptionsManager.cs]: @kvakvs you mean this code that does nothing? 🧐 
image

Comment (kvakvs) [reply TLM/TLM/Manager/Impl/OptionsManager.cs]: It subscribes to locale change in localemanager, and that's assembly-csharp, the C:S DLL

Comment (aubergine10) [reply TLM/TLM/Manager/Impl/OptionsManager.cs]: Ah, yeah, there's two places language can change - the mod option (global config based) and if that's `null` then we look at the game language IIRC so need to listen for vanilla game language change (and have some conversion between its language codes, which can be modded, to our language codes).

@krzychu124 I did a load of digging in https://github.com/CitiesSkylinesMods/TMPE/issues/1379 and traced what I found in comments there which might be of some use to getting idea of how the locale stuff all fits together.

Comment (krzychu124) [reply TLM/TLM/Manager/Impl/OptionsManager.cs]: > It subscribes to locale change in localemanager, and that's assembly-csharp, the C:S DLL

`LocaleManager` is in `ColossalManaged.dll` but that doesn't even matter here.
@kvakvs that code is in `KeybindSettingsBase` and method `OnLocaleChanged` does literally nothing. Body in our method is empty and you probably meant `OnLocaleChanged` but from the `UIComponent` (`KeybindSettingsBase` extends `UICustomControl` **which is not** `UIComponent` - `UICustomControl` only hold reference to `UIComponent`). 

It looks like a bug or some leftovers after refactoring.

Comment (chameleon-tbn) [reply TLM/TLM/Manager/Impl/OptionsManager.cs]: something seems to be wrong....

now the UI disapears if the pathfind is turned off :D

image

Comment (chameleon-tbn) [reply TLM/TLM/Manager/Impl/OptionsManager.cs]: So final Test... With the correct DLL 😁

It works!

**Review by chameleon-tbn — APPROVED** [review]
Tested with a Player who Had that issue every time. Now fixed :)

**Review by aubergine10 — APPROVED** [review]
LGTM 👍 

Also noticeably faster when changing features now that it's not unnecessarily loading textures :)

File: TLM/TLM/Manager/Impl/OptionsManager.cs (hunk 1 above)
Comment (aubergine10) [reply TLM/TLM/Manager/Impl/OptionsManager.cs]: @krzychu124 does the stuff about empty `OnLocaleChanged` need tracking in separate issue?

otherwise this conversation block can be marked resolved

Comment (krzychu124) [reply TLM/TLM/Manager/Impl/OptionsManager.cs]: I would create new issue and we will see what to do with that thing (what was the intention and if is there any bug). This conversation can be marked as resolved.

Comment (aubergine10) [reply TLM/TLM/Manager/Impl/OptionsManager.cs]: Created issue: https://github.com/CitiesSkylinesMods/TMPE/issues/1520

**Comment by aubergine10** [comment]
merge?
