### PR TITLE
harmon patcher continues on error

### LINKED ISSUE #1074: patcher to continue on error
Harmony.PatchAll stops as soon as it faces the first exception.
but I think it should continue to the next patch.
I have done this in my KianCommons. I can copy this code to TMPE
https://github.com/kianzarrin/KianCommons/blob/59e0574d7433e14e667daf0680af4dce61657c96/KianCommons/Patches/HarmonyUtil.cs#L105

### LINKED ISSUE #1075: Logger needs Log.Exception method
~~it might be a bit confusing how to log exception, stack trace, inner exceptions, ...~~ . better to do it in a centralized way.
also, this function should have the option to show error dialog.

### PR DESCRIPTION
**Pull request by kianzarrin**
fixes #1074
- Harmony patcher continues on error.
- also it logs which functions ~~have been patched~~ failed patching.
fixes #1075:
- I added an extension method to log exceptions. now logging exception is done in a central place and can be made consistent/globally improved.
- it's not in the log class because I needed CO reference.

https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=1074-patcher

~~depends on PR #1072~~
blocks PR #1077

### CODE REVIEW

**Comment by kianzarrin** [comment]
I removed the patch logs.

File: TLM/TLM/Util/Shortcuts.cs [hunk 1]
```diff
@@ -160,6 +161,19 @@ internal static class Shortcuts {
             }
         }
 
+        internal static void LogException(this Exception ex, bool showInPanel = false) {
```
Comment (krzychu124) [inline TLM/TLM/Util/Shortcuts.cs:164]: Why not in Log class?

Comment (kianzarrin) [reply TLM/TLM/Util/Shortcuts.cs:164]: > it's not in the log class because I needed CO reference.

**Review by kvakvs — APPROVED** [review]
Looks fine
But please make the error text better (spelling, remove !!!!!!, etc) and report it to user in a readable way.

File: TLM/TLM/Patcher.cs [hunk 2]
```diff
@@ -4,29 +4,40 @@ namespace TrafficManager {
...
+    using CitiesHarmony.API;
+    using System.Runtime.CompilerServices;
+    using System.Reflection;
+    using TrafficManager.Util;
+    using System.Linq;
     public static class Patcher {
         private const string HARMONY_ID = "de.viathinksoft.tmpe";
 
+        private const string ERROR_MESSAGE =
+                    "****** ERRRROOORRRRRR!!!!!!!!!! **************\n" +
```
[the remark this answers is not in the document]
Comment (kianzarrin) [reply TLM/TLM/Patcher.cs]: Fixed

**Review by kvakvs — APPROVED** [review]
Nice

File: TLM/TLM/Patcher.cs [hunk 3]
```diff
@@ -41,19 +55,40 @@ public static class Patcher {
...
                 Log.Info("TMPE patches installed successfully");
             }
         }
 
+        /// <summary>
+        /// applies all attribute diven harmony patches.
+        /// continues on error.
+        /// </summary>
+        /// <returns>false if exception happens, true otherwise</returns>
+        [MethodImpl(MethodImplOptions.NoInlining)]
```
Comment (krzychu124) [inline TLM/TLM/Patcher.cs:73]: That method will never get inlined because of try...catch inside

File: TLM/TLM/Patcher.cs [hunk 4]
```diff
@@ -41,19 +55,40 @@ public static class Patcher {
...
+        static bool PatchAll() {
+            bool success = true;
+            var harmony = new Harmony(HARMONY_ID);
+            var assembly = Assembly.GetExecutingAssembly();
+            foreach(var type in AccessTools.GetTypesFromAssembly(assembly)) {
```
Comment (krzychu124) [inline TLM/TLM/Patcher.cs:78]: [Note]
Theoretically may throw exception if somehow dependency assembly could not be resolved.
Whole Install method will break, TM:PE managers won't get notified (in `LoadingExtension.Load()`)

**Review by krzychu124 — CHANGES_REQUESTED** [review]
Quick review

File: TLM/TLM/Patcher.cs (hunk 4 above)
Comment (kianzarrin) [reply TLM/TLM/Patcher.cs:78]: it does not hurt to emphasize :). even if not useful to compiler it acts like doc so that programmer knows this function must not be inlined.

File: TLM/TLM/Patcher.cs (hunk 3 above)
Comment (kianzarrin) [reply TLM/TLM/Patcher.cs:73]: it does not hurt to emphasize :). even if not useful to the compiler it acts like doc so that programmer knows this function must not be inlined.

**Review by krzychu124 — APPROVED** [review]
Ok 👍

**Review by chameleon-tbn — APPROVED** [review]
Okay for me
