### PR TITLE
Fix wrong texture atlas in scenario editor

### LINKED ISSUE #1449: Blank TM:PE toolbar buttons in Scenario Editor
> _Originally posted by @kianzarrin in https://github.com/CitiesSkylinesMods/TMPE/issues/1422#issuecomment-1056996064_ :
>  
> blank-buttons
> image
red arrow is bad green arrow is good

### LINKED ISSUE #1450: Background textures missing in Scenario Editor (and others?)
As mentioned by @krzychu124 in https://github.com/CitiesSkylinesMods/TMPE/issues/1449#issuecomment-1057372799 :

> some textures from vanilla atlas are not available in Scenario editor so backgrounds are blank.

Example (from a winter map hence snow in bg):

image

### PR DESCRIPTION
**Pull request by krzychu124**
- fixed wrong texture atlas used in scenario editor (thanks @kianzarrin for half of the work done via git patch file) 🙂 
- implemented `UITextureAtlas` release function, attached to `MainMenuWindow.OnDestroy()`
- **fixed memory leak on exit from Lane Arrows tool. (window improperly destroyed)**

Closes #1449 
Closes #1450

### CODE REVIEW

File: TLM/TLM/UI/WhatsNew/WhatsNewPanel.cs [hunk 1]
```diff
@@ -1,6 +1,7 @@
 namespace TrafficManager.UI.WhatsNew {
     using System;
     using System.Collections.Generic;
+    using System.Net.Configuration;
```
Comment (aubergine10) [inline TLM/TLM/UI/WhatsNew/WhatsNewPanel.cs:4]: ?

File: TLM/TLM/UI/MainMenu/DebugMenu.cs [hunk 2]
```diff
@@ -15,6 +15,7 @@ namespace TrafficManager.UI.MainMenu {
     using TrafficManager.Lifecycle;
     using TrafficManager.Manager.Impl;
     using TrafficManager.Util.Extensions;
+    using TrafficManager.U;
```
Comment (aubergine10) [inline TLM/TLM/UI/MainMenu/DebugMenu.cs:18]: Very minor, can be ignored: Could this be done same for all updated files - eg. so everything is `TextureUtil.Ingame` rather than `U.TextureUtil.Ingame` (or vice versa)?

File: TLM/TLM/UI/WhatsNew/WhatsNewPanel.cs (hunk 1 above)
Comment (krzychu124) [reply TLM/TLM/UI/WhatsNew/WhatsNewPanel.cs:4]: hehe, probably I made a typo and it automatically imported this thing 😂

**Review by aubergine10 — APPROVED** [review]
Built from source, tested in scenario editor - LGTM 👍

**Comment by krzychu124** [comment]
_I've added fix for Lane Arrow window memory leak on close._

**Review by kianzarrin — APPROVED** [review]
