### PR TITLE
fix uturn policy on T junctions

### LINKED ISSUE #347: T Junctions don't seem to have u-turns occur
### Description
Perhaps I can use better words, but when I put in a metro station with several parking garages, all the cars seem to have a rather peculiar habit of doing a loop, even when the u-turns policy is enabled. 

### Reproduction Steps
Add more steps as nessecary.
1. Select any T-Junction on the game (preferably with the six-lane roads)
2. Allow the policy for u-turns to be enabled
3. Watch.

### Mod List
Please list the mods enabled when you noticed the bug.

[config SubaruSVX.docx](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3239814/config.SubaruSVX.docx)

### Output Log
[Player.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3239789/Player.log)

### Savegame (Optional)
https://steamcommunity.com/sharedfiles/filedetails/?id=1736078702

### Screenshots (Optional)
Screenshot 11
Screenshot 12
Screenshot 13
Screenshot 14
Screenshot 15

### LINKED ISSUE #900: Breaking path finding on cul-de-sacs
Experiencing weird pathfinder behaviour.

Hearses can't find path to a house on an outgoing side of the cul-de-sac road.

I've illustrated the initial situation with temporary bus line. Having placed the starting bus stop on an incoming side of the two segment cul-de-sac. Path is found after the u-trun to the left segment, but it cannot find path to the right segment. However, it can find path straight from left to right segment.

This is Network Extensions' Zonable Promenade. It has one lane.

image
image
image

If I dissolve the node with Elektrix's tool (so that the whole street consists of one segment), I am able to draw path (by placing bus stops) fine around this road fine for several seconds. Then it looses the ability to turn around. If I place a node, the story starts over.

### PR DESCRIPTION
**Pull request by kianzarrin**
fixes #347 
fixes #900

2 commits:
1st commit : simplifies code without any effective change the code.
2nd commit: fixes the u-turn issue

here U-turn routing of type `LaneEndTransitionType.Default` happens if it is a junction with 2 segments  but not when it is a junction with 3 segments.
https://github.com/CitiesSkylinesMods/TMPE/blob/a7d644629bd2b5ceeff5b5e61b4dca9e07550e8d/TLM/TLM/Manager/Impl/RoutingManager.cs#L907
note : `nextIsRealJunction = nextNode.CountSegments() >= 3`

So basically what this means is we have the picture bellow: 
image
an orange relaxed u-turn routing on one side and a green default u-turn routing on the other side

----
How to test:

TMPE build:  https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=T-uturn-347

We can  use bus stops to see if u-turn is possible. By using the "Buses may ignore lane arrows" policy we can test relaxed/default lane routing.
Buses may Ignore lane arrows policy (in original TMPE. this PR fixes this) = off
image
image

Buses may Ignore lane arrows policy = on
image

### CODE REVIEW

File: TLM/TLM/Manager/Impl/RoutingManager.cs [hunk 1]
```diff
@@ -1968,7 +1967,7 @@ bool laneChangesAllowed
                                     // force u-turns to happen on the innermost lane
                                     ++compatibleLaneDist;
                                     nextCompatibleTransitionDatas[nextTransitionIndex].type =
-                                        LaneEndTransitionType.Relaxed;
+                                        LaneEndTransitionType.Relaxed; // TODO : normal when u-turn allowed
```
Comment (kianzarrin) [inline TLM/TLM/Manager/Impl/RoutingManager.cs]: ignore this. I deleted this comment in the next commit

**Review by krzychu124 — APPROVED** [review]
looks ok, not tested in game yet

**Review by DaEgi01 — APPROVED** [review]
