### PR TITLE
Fix regression with version naming

### LINKED ISSUE #1566: What's New panel - support for hotfix version
### Describe the problem
Recently pushed `What's New` update #1563 broke the changelog parsing _(I hotfixed the hotfix and uploaded working solution to the workshop 😅 )_. `Version` accepts only up to 4 comma separated numbers and fails on reading other text characters.

### Notes or questions?
Should be introduce `TMPEVersion` type in replacement of C# `Version` and implement additional parser + comparer?
How hotfix releases should be displayed in the `What's New` panel? 
I think we should display hotfix(es) on top and then below the version that was hotfixed so the user will see all changes regards to specific version instead of changelog just from the hotfix(panel stops loading anything older than last shown version).

@aubergine10 ideas?

### PR DESCRIPTION
**Pull request by krzychu124**
Simplest possible fix for unsupported version string supplied to the C# `Version` constructor

In the future updates we should ensure that last number of version string `x.x.x.x` will be dedicated for hotfix releases so: 
`11(12?).<major - stable releases>.<minor - test releases>.<hotfix>`

Closes #1566

### CODE REVIEW

**Review by aubergine10 — APPROVED** [review]
👍

File: TLM/TLM/UI/WhatsNew/WhatsNew.cs [hunk 1]
```diff
@@ -102,7 +102,8 @@ public class WhatsNew {
                     && lineKeyword == MarkupKeyword.VersionStart) {
 
                     var changelog = new Changelog() {
-                        Version = new Version(text),
+                        // version text can be 1.2.3.4 or 1.2.3.4-hotfix-<number>
```
Comment (aubergine10) [inline TLM/TLM/UI/WhatsNew/WhatsNew.cs:105]: Should the end of that comment be `1.2.3-hotfix-<number>` ?

Comment (krzychu124) [reply TLM/TLM/UI/WhatsNew/WhatsNew.cs:105]: probably in the future but now it's `1.2.3.4-hotfix-<number>` -> `11.6.5.2-hotfix-1` and Version accepts only `1.2.3.4` and no text at all

**Comment by aubergine10** [comment]
can this be merged, it's making it difficult to test other PRs without alering the whatsnew txt file each time switching between PRs
