### PR TITLE
Place Intersection improvements, bugfixing 

### LINKED ISSUE #1307: Mod conflict IMT, NCR - Place intersection data restore failing
### Describe the problem

_Intersection Marking Tool_, _Node Controller Renewal_ patches silently break TMPE `TrafficManager.Patches._BuildingDecoration.LoadPathsPatch` patch (probably our instruction assertion has a bug somewhere).

### Steps to reproduce

1. Subscribe and enable Intersection Marking Tool
2. Subscribe and enable Node Controller Renewal
3. Try placing asset with saved TM:PE configuration

### PR DESCRIPTION
**Pull request by krzychu124**
Closes #1307 

 - changed patch instruction injection from _inserting before list clear call_ to _inserting after end of the loop_ (reduces chance of incompatibilities in case of transpiling the same method by the other mods)
 - delaying traffic rules application to the end of simulation step **(not perfect solution)**
 - removed calls forcing node/segment recalculation - may trigger additional calls to `(BuildingDecoration.LoadPaths()` breaking traffic rules application and also other mods relying on contents of `tempNodeBuffer`/`tempSegmentBuffer` collections

[Build zip](https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=1307-place-intersection-restore-bugfix)

### CODE REVIEW

**Review by aubergine10 — APPROVED** [review]
Built from source as `RELEASE`, tested in game, didn't encounter any problems.

**Review by chameleon-tbn — APPROVED** [review]
tested ingame, all good.

File: TLM/TLM/Patch/_BuildingDecoration/LoadPathsPatch.cs [hunk 1]
```diff
@@ -18,21 +20,24 @@ public class LoadPathsPatch {
...
+                ?? throw new Exception("Could not find AfterIntersectionBuilt()");
 
             List<CodeInstruction> codes = TranspilerUtil.ToCodeList(instructions);
-            bool comp(int i) =>
-                codes[i].opcode == OpCodes.Ldfld && codes[i].operand == fTempNodeBuffer &&
-                codes[i + 1].opcode == OpCodes.Callvirt && codes[i + 1].operand == mClear;
-            int index = TranspilerUtil.SearchGeneric(codes, comp, index: 0, counter: 2);
-            index -= 1; // index to insert instructions.
+
+            bool compareFn(int i) =>
```
Comment (kianzarrin) [inline TLM/TLM/Patch/_BuildingDecoration/LoadPathsPatch.cs:35]: [lowp] now that I think about it, this should be called predicate.
