### PR TITLE
Fix game version warning

### LINKED ISSUE #697: The `--continuelastsave` launch option skips mod checker panel
Since new launcher, the `--continuelastsave` launch option (what happens when user clicks "Resume" on the launcher app) makes game automatically reload last save.

If TM:PE finds mod incompatibility, it shows the purple warning dialog expecting main menu to remain in background. However, `--continuelastsave` just closes all that down and dives in to game. From user perspective, a purple panel flickers up for less than a second then disspaears again as their last save starts to load.

So we need some way to disable `--continuelastsave` if mod incompatibility is found.

I'm not entirely sure how to do that. I suspect by the time we get round to displaying the "incompatibel mods found" panel, the game has already kicked in loading of last savegame.

### LINKED ISSUE #1309: Typo in game version warning panel
### Describe the problem

Minor UI issue (will send PR to fix)....

```
Info 41.7936109: Expected C:SL v1.14.0-f4 - Actual C:SL v1.13.3-f9
```

It's saying "newer game version" - should be "older".

image

### PR DESCRIPTION
**Pull request by aubergine10**
Fixes #1309
Fixes #697

Game version warning message was "inverted" (eg. if game too old it was saying TM:PE too old, and vice versa).

New message looks like this - title changes depending on what is too old, but message stays same.

image

Additionally the auto-resume feature added by Paradox Launcher will be cancelled if compatibility issues (either game version or mod compatibility checker) are found.

### CODE REVIEW

File: TLM/TLM/Util/VersionUtil.cs [hunk 1]
```diff
@@ -128,27 +128,24 @@ public static class VersionUtil {
                 Version current = CurrentGameVersion.Take(VERSION_COMPONENTS_COUNT);
                 Version expected = ExpectedGameVersion.Take(VERSION_COMPONENTS_COUNT);
 
-                if (current < expected) {
-                    // game too old
+                if (current != expected) {
```
Comment (krzychu124) [inline TLM/TLM/Util/VersionUtil.cs:131]: At first I thought it's a typo, but as the new update brings breaking changes it might be done this way.

**Review by krzychu124 — APPROVED** [review]
Looks good 👍

File: TLM/TLM/Util/VersionUtil.cs (hunk 1 above)
Comment (aubergine10) [reply TLM/TLM/Util/VersionUtil.cs:128]: See comment above `VERSION_COMPONENTS_COUNT` in code - CO update that part of the version whenever there are likely to be mod-breaking changes.

I can change it back to `<` | `>` if desired.

**Comment by aubergine10** [comment]
https://github.com/CitiesSkylinesMods/TMPE/pull/1310/commits/659e59dfff999c573a8b28697db30d71c611c063 : The launcher "Resume" feature will now be halted if there is a game version or mod compatibility issue, ensuring the user stays at main menu where the dialog/panel is shown.

File: TLM/TLM/Util/VersionUtil.cs (hunk 1 above)
Comment (krzychu124) [reply TLM/TLM/Util/VersionUtil.cs:128]: > I can change it back to < | > if desired.

No need, it's OK.

**Comment by aubergine10** [comment]
ready for review/merge :)

**Comment by krzychu124** [comment]
Hmmm it looks like it does not work for me 🤔 I saw dialog for half second and loading started...

**Comment by aubergine10** [comment]
Urg, maybe they changed something - or the checks are kicking in too late in the lifecycle?

**Comment by krzychu124** [comment]
It's triggered in `LoadIntroComplete` (`m_introLoaded` event) so a bit too late
```cs
Error 14.9722435: TM:PE 11.6.3 TEST is designed for Cities: Skylines 1.14.0-f4. However you are using Cities: Skylines 1.13.3-f9 - this is likely to cause severe problems or crashes.

Please ensure you're using the right version of TM:PE for this version of Cities: Skylines before proceeding, or disable TM:PE until the problem is resolved. If you need help, contact us via Steam Workshop page or Discord chat.
   at CSUtil.Commons.Log.LogToFile(System.String log, LogLevel level)
   at CSUtil.Commons.Log.Error(System.String s)
   at TrafficManager.Util.VersionUtil.CheckGameVersion()
   at TrafficManager.Lifecycle.TMPELifecycle.CompatibilityCheck()
   at LoadingManager+<LoadIntroComplete>c__Iterator8.MoveNext()
   at LoadingManager.FpsBoosterUpdate()
   at BehaviourUpdater.Updater.Update()
   ```

**Comment by aubergine10** [comment]
Here, specifically:

image

**Comment by aubergine10** [comment]
Oh, wait, I know what I did wrong...

I need to grab tbe value early, set it false, then if checks pass with no problems set it true and continue.

1 sec, will update code...

**Comment by krzychu124** [comment]
> Oh, wait, I know what I did wrong...
> 
> I need to grab tbe value early, set it false, then if checks pass with no problems set it true and continue.
> 
> 1 sec, will update code...

I was about to say that, since user can't make any decision if continue or not...

**Comment by aubergine10** [comment]
Stopping it in `TMPELifecycle.StartMod();` should be early enough, yes?

**Comment by krzychu124** [comment]
> Stopping it in `TMPELifecycle.StartMod();` should be early enough, yes?

Hehe, you can't do that earlier (that method is called in OnEnabled)

**Comment by aubergine10** [comment]
Constructor of `TrafficManagerMod` or is that still too late?

**Comment by krzychu124** [comment]
> Constructor of `TrafficManagerMod` or is that still too late?

.ctor is called right before OnEnabled so either this or that. In any means looking at detailed log of initialization of game components both are good enough spots

**Comment by aubergine10** [comment]
ok, try that :)

**Comment by krzychu124** [comment]
Hehe, I thought you will check for incompatibilities and disable if necessary then wait to show dialog with warning 😄 

Anyways, feature is working as it should. Merging...

**Comment by aubergine10** [comment]
I can't check incompatibilities of mods reliably at that stage (tried that back in #699 )
