### PR TITLE
TMPE settings not applied immediately after loading the savegame

### LINKED ISSUE #1624: TMPE settings are not applied correctly after loading a savegame
### Describe the problem

TM:PE is patching vanilla methods too late in the loading process so not all network changes are registered resulting in missing network updates (settings are not reapplied after update from other mod)

### Steps to reproduce

1. Make sure you subscribe Node Controller or Node Controller Renewal, use local version of TMPE or subscribe before NC
2. Create junction and setup some non-standard lane connections (which force lane arrow to be different than default)
3. Alter the junction with Node Controller slightly
4. Save the game
5. Restart game and load the savegame, don't start simulation (use option to pause after load)
6. Observe lane arrows - they won't match lane connections despite everything is correctly loaded
7. Run simulation for few seconds to see that everything updates and start working correctly (touch with MoveIt or NC might be required at last resort option to update intersection state)

### PR DESCRIPTION
**Pull request by krzychu124**
#1624 

- moved Harmony patches installation to earlier step of loading process to prevent network update desync and make it mod load order independent
- the change does not break hot-reload - in both situations mod initialization process goes in the same order

#### Other
- fixed `NullReferenceException` on exit to the Main menu or when user try to reload savegame

Build [zip](https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=bugfix/1624-network-not-reflecting-mod-settings)

### CODE REVIEW

**Review by kianzarrin — APPROVED** [review]
as discussed on discord this is a quick fix. we need to see if we can apply all patches in preload.
also would be nice to avoid the need to update all lane arrows for dedicated turning lanes policy to save loading times.

don't forget to reopen #1624 after merge

File: TLM/TLM/UI/TrafficManagerTool.cs [hunk 1]
```diff
@@ -1660,7 +1660,9 @@ void DefaultRenderOverlay(RenderManager.CameraInfo cameraInfo)
         }
 
         public void RemoveUUIButton() {
-            Destroy(UUIButton?.gameObject);
+            if (UUIButton) {
+                Destroy(UUIButton.gameObject);
```
Comment (kianzarrin) [inline TLM/TLM/UI/TrafficManagerTool.cs:1664]: maybe also update UUI version from NuGet?

**Review by chameleon-tbn — APPROVED** [review]
seems to work now flawless. at least i not able to reproduce my issue any more
